[package]
name = "translate"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.5"

[[bin]]
name="main"
path="src/main_1.rs"

[[bin]]
name="test"
path="src/test_main.rs"
