use crate::*;


pub struct EState {
    pub strm: Option<Box<BzStream>>,
    pub mode: Int32,
    pub state: Int32,
    pub avail_in_expect: UInt32,
    pub arr1: Option<Box<[UInt32]>>,
    pub arr2: Option<Box<[UInt32]>>,
    pub ftab: Option<Box<[UInt32]>>,
    pub origPtr: Int32,
    pub ptr: Option<Box<[UInt32]>>,
    pub block: Option<Box<[UChar]>>,
    pub mtfv: Option<Box<[UInt16]>>,
    pub zbits: Option<Box<[UChar]>>,
    pub workFactor: Int32,
    pub state_in_ch: UInt32,
    pub state_in_len: Int32,
    pub rNToGo: Int32,
    pub rTPos: Int32,
    pub nblock: Int32,
    pub nblockMAX: Int32,
    pub numZ: Int32,
    pub state_out_pos: Int32,
    pub nInUse: Int32,
    pub inUse: [Bool; 256],
    pub unseqToSeq: [UChar; 256],
    pub bsBuff: UInt32,
    pub bsLive: Int32,
    pub blockCRC: UInt32,
    pub combinedCRC: UInt32,
    pub verbosity: Int32,
    pub blockNo: Int32,
    pub blockSize100k: Int32,
    pub nMTF: Int32,
    pub mtfFreq: [Int32; 258],
    pub selector: [UChar; 2 + (900000 / 50)],
    pub selectorMtf: [UChar; 2 + (900000 / 50)],
    pub len: [[UChar; 258]; 6],
    pub code: [[Int32; 258]; 6],
    pub rfreq: [[Int32; 258]; 6],
    pub len_pack: [[UInt32; 4]; 258],
}

