[package]
name = "translate"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
ncurses = "5.101.0"
libc = "0.2.153"
rand = "0.8.5"

[[bin]]
name="robotfindskitten"
path="src/robotfindskitten_main.rs"
