typedef enum BrotliEncoderParameter
{
  BROTLI_PARAM_MODE = 0,
  BROTLI_PARAM_QUALITY = 1,
  BROTLI_PARAM_LGWIN = 2,
  BROTLI_PARAM_LGBLOCK = 3,
  BROTLI_PARAM_DISABLE_LITERAL_CONTEXT_MODELING = 4,
  BROTLI_PARAM_SIZE_HINT = 5,
  BROTLI_PARAM_LARGE_WINDOW = 6,
  BROTLI_PARAM_NPOSTFIX = 7,
  BROTLI_PARAM_NDIRECT = 8,
  BROTLI_PARAM_STREAM_OFFSET = 9
} BrotliEncoderParameter
/*** DEPENDENCIES:
***/


