enum input_csi_type
{
  INPUT_CSI_CBT,
  INPUT_CSI_CNL,
  INPUT_CSI_CPL,
  INPUT_CSI_CUB,
  INPUT_CSI_CUD,
  INPUT_CSI_CUF,
  INPUT_CSI_CUP,
  INPUT_CSI_CUU,
  INPUT_CSI_DA,
  INPUT_CSI_DA_TWO,
  INPUT_CSI_DCH,
  INPUT_CSI_DECSCUSR,
  INPUT_CSI_DECSTBM,
  INPUT_CSI_DL,
  INPUT_CSI_DSR,
  INPUT_CSI_ECH,
  INPUT_CSI_ED,
  INPUT_CSI_EL,
  INPUT_CSI_HPA,
  INPUT_CSI_ICH,
  INPUT_CSI_IL,
  INPUT_CSI_RCP,
  INPUT_CSI_REP,
  INPUT_CSI_RM,
  INPUT_CSI_RM_PRIVATE,
  INPUT_CSI_SCP,
  INPUT_CSI_SGR,
  INPUT_CSI_SM,
  INPUT_CSI_SM_PRIVATE,
  INPUT_CSI_SU,
  INPUT_CSI_TBC,
  INPUT_CSI_VPA,
  INPUT_CSI_WINOPS
}
/*** DEPENDENCIES:
***/


