enum input_esc_type
{
  INPUT_ESC_DECALN,
  INPUT_ESC_DECKPAM,
  INPUT_ESC_DECKPNM,
  INPUT_ESC_DECRC,
  INPUT_ESC_DECSC,
  INPUT_ESC_HTS,
  INPUT_ESC_IND,
  INPUT_ESC_NEL,
  INPUT_ESC_RI,
  INPUT_ESC_RIS,
  INPUT_ESC_SCSG0_OFF,
  INPUT_ESC_SCSG0_ON,
  INPUT_ESC_SCSG1_OFF,
  INPUT_ESC_SCSG1_ON,
  INPUT_ESC_ST
}
/*** DEPENDENCIES:
***/


