#include <gen_char_category_table.c>
#include <stdio.h>
#include <url_char_category.h>

enum Category
{
  Scheme = 0x01,
  Unreserved = 0x02,
  GenDelim = 0x04,
  SubDelim = 0x08,
  PCharSlash = 0x10,
  HexDigit = 0x20,
  Query = 0x40,
  Fragment = 0x40,
  Userinfo = 0x80,
  IPv6Char = 0x100
};
unsigned char_cat[256];
const char * const alnum = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
const char * const unreserved = "-._~";
const char * const subdelim = "!$&'()*+,;=";
void fill(unsigned value, const char *alnum, const char *special)
{
  unsigned int special_idx = 0;
  unsigned int alnum_idx = 0;
  for (; alnum[alnum_idx]; alnum_idx += 1)
  {
    char_cat[(unsigned char) alnum[alnum_idx]] |= value;
  }

  for (; special[special_idx]; special_idx += 1)
  {
    char_cat[(unsigned char) special[special_idx]] |= value;
  }

}

void print_table()
{
  printf("// This file is generated by gen_char_category_table. DO NOT EDIT IT BY HAND!\n\nstatic const unsigned short char_cat[256] = {\n//   .0     .1     .2     .3     .4     .5     .6     .7     .8     .9     .A     .B     .C     .D     .E     .F\n");
  for (unsigned y = 0; y < 16; y += 1)
  {
    putchar(' ');
    for (unsigned x = 0; x < 16; x += 1)
    {
      const unsigned offset = (y * 16) + x;
      printf(" 0x%03x%c", char_cat[offset], (offset == 255) ? (' ') : (','));
    }

    printf(" // %01X0 ... %01XF\n", y, y);
  }

  printf("};\n\n");
}

int main()
{
  fill(Scheme, alnum, "+-.");
  fill(Unreserved, alnum, unreserved);
  fill(GenDelim, alnum, ":/?#[]@");
  fill(SubDelim, alnum, subdelim);
  fill(PCharSlash, alnum, ":@/%");
  fill(PCharSlash, unreserved, subdelim);
  fill(HexDigit, "0123456789", "abcdefABCDEF");
  fill(Query, alnum, "/?:@%");
  fill(Query, unreserved, subdelim);
  fill(Userinfo, alnum, ":%");
  fill(Userinfo, unreserved, subdelim);
  fill(IPv6Char, "0123456789", "abcdefABCDEF:");
  print_table();
}


enum Category
{
  Scheme = 0x01,
  Unreserved = 0x02,
  GenDelim = 0x04,
  SubDelim = 0x08,
  PCharSlash = 0x10,
  HexDigit = 0x20,
  Query = 0x40,
  Fragment = 0x40,
  Userinfo = 0x80,
  IPv6Char = 0x100
};
unsigned char_cat[256];
const char * const alnum = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
const char * const unreserved = "-._~";
const char * const subdelim = "!$&'()*+,;=";
void fill(unsigned value, const char *alnum, const char *special)
{
  unsigned int special_idx = 0;
  unsigned int alnum_idx = 0;
  for (; alnum[alnum_idx]; alnum_idx += 1)
  {
    char_cat[(unsigned char) alnum[alnum_idx]] |= value;
  }

  for (; special[special_idx]; special_idx += 1)
  {
    char_cat[(unsigned char) special[special_idx]] |= value;
  }

}

void print_table()
{
  printf("// This file is generated by gen_char_category_table. DO NOT EDIT IT BY HAND!\n\nstatic const unsigned short char_cat[256] = {\n//   .0     .1     .2     .3     .4     .5     .6     .7     .8     .9     .A     .B     .C     .D     .E     .F\n");
  for (unsigned y = 0; y < 16; y += 1)
  {
    putchar(' ');
    for (unsigned x = 0; x < 16; x += 1)
    {
      const unsigned offset = (y * 16) + x;
      printf(" 0x%03x%c", char_cat[offset], (offset == 255) ? (' ') : (','));
    }

    printf(" // %01X0 ... %01XF\n", y, y);
  }

  printf("};\n\n");
}

int main()
{
  fill(Scheme, alnum, "+-.");
  fill(Unreserved, alnum, unreserved);
  fill(GenDelim, alnum, ":/?#[]@");
  fill(SubDelim, alnum, subdelim);
  fill(PCharSlash, alnum, ":@/%");
  fill(PCharSlash, unreserved, subdelim);
  fill(HexDigit, "0123456789", "abcdefABCDEF");
  fill(Query, alnum, "/?:@%");
  fill(Query, unreserved, subdelim);
  fill(Userinfo, alnum, ":%");
  fill(Userinfo, unreserved, subdelim);
  fill(IPv6Char, "0123456789", "abcdefABCDEF:");
  print_table();
}

