[package]
name = "translate_without_break_down"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name="gen_char_category_table"
path="src/gen_char_category_table_main.rs"

[[bin]]
name="test"
path="src/test_main.rs"
