/* zzero */
zsets(a, "-5");
assert(zzero(a), == 0);

zsets(a, "3");
assert(zzero(a), == 0);

zsets(a, "-1");
assert(zzero(a), == 0);

zsets(a, "0");
assert(zzero(a), == 1);

zsets(a, "0");
assert(zzero(a), == 1);


/* zsignum */
zsets(a, "0");
assert(zsignum(a), == 0);

zsets(a, "-3");
assert(zsignum(a), == -1);

zsets(a, "1");
assert(zsignum(a), == 1);

zsets(a, "-3");
assert(zsignum(a), == -1);

zsets(a, "-3");
assert(zsignum(a), == -1);


/* zeven_nonzero */
zsets(a, "-1");
assert(zeven_nonzero(a), == 0);

zsets(a, "4");
assert(zeven_nonzero(a), == 1);

zsets(a, "-1");
assert(zeven_nonzero(a), == 0);

zsets(a, "2");
assert(zeven_nonzero(a), == 1);

zsets(a, "2");
assert(zeven_nonzero(a), == 1);


/* zodd_nonzero */
zsets(a, "1");
assert(zodd_nonzero(a), == 1);

zsets(a, "1");
assert(zodd_nonzero(a), == 1);

zsets(a, "-2");
assert(zodd_nonzero(a), == 0);

zsets(a, "4");
assert(zodd_nonzero(a), == 0);

zsets(a, "2");
assert(zodd_nonzero(a), == 0);


/* zeven */
zsets(a, "1");
assert(zeven(a), == 0);

zsets(a, "2");
assert(zeven(a), == 1);

zsets(a, "2");
assert(zeven(a), == 1);

zsets(a, "2");
assert(zeven(a), == 1);

zsets(a, "1");
assert(zeven(a), == 0);


/* zcmp */
zsets(a, "-1");
zsets(b, "-1");
assert(zcmp(a, b), == 0);

zsets(a, "1");
zsets(b, "2");
assert(zcmp(a, b), == -1);

zsets(a, "1");
zsets(b, "-1");
assert(zcmp(a, b), == 1);

zsets(a, "3");
zsets(b, "-1");
assert(zcmp(a, b), == 1);

zsets(a, "0");
zsets(b, "-7");
assert(zcmp(a, b), == 1);


/* zcmpi */
zsets(a, "2");
assert(zcmpi(a, 4614593351115531455LL), == -1);

zsets(a, "1");
assert(zcmpi(a, 7905145703066210678LL), == -1);

zsets(a, "-1");
assert(zcmpi(a, -8143282188092715279LL - 1LL), == 1);

zsets(a, "0");
assert(zcmpi(a, 8953541771590140542LL), == -1);

zsets(a, "3");
assert(zcmpi(a, 6565218600223342386LL), == -1);


/* zcmpu */
zsets(a, "2");
assert(zcmpu(a, 5535566519162140002ULL), == -1);

zsets(a, "4");
assert(zcmpu(a, 13611530411809325772ULL), == -1);

zsets(a, "0");
assert(zcmpu(a, 9875490214925525992ULL), == -1);

zsets(a, "-1");
assert(zcmpu(a, 12956477157167443725ULL), == -1);

zsets(a, "4");
assert(zcmpu(a, 10949271873353929376ULL), == -1);


/* zcmpmag */
zsets(a, "-4");
zsets(b, "2");
assert(zcmpmag(a, b), == 1);

zsets(a, "1");
zsets(b, "6");
assert(zcmpmag(a, b), == -1);

zsets(a, "-1");
zsets(b, "3");
assert(zcmpmag(a, b), == -1);

zsets(a, "4");
zsets(b, "3");
assert(zcmpmag(a, b), == 1);

zsets(a, "1");
zsets(b, "5");
assert(zcmpmag(a, b), == -1);


/* zodd */
zsets(a, "-6");
assert(zodd(a), == 0);

zsets(a, "-2");
assert(zodd(a), == 0);

zsets(a, "3");
assert(zodd(a), == 1);

zsets(a, "1");
assert(zodd(a), == 1);

zsets(a, "-1");
assert(zodd(a), == 1);


/* zabs */
zsets(a, "-1");
zabs(b, a);
zabs(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "1");

zsets(a, "-1");
zabs(b, a);
zabs(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "1");

zsets(a, "-1");
zabs(b, a);
zabs(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "1");

zsets(a, "3");
zabs(b, a);
zabs(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "3");

zsets(a, "-2");
zabs(b, a);
zabs(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "2");


/* zneg */
zsets(a, "2");
zneg(b, a);
zneg(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-2");

zsets(a, "-3");
zneg(b, a);
zneg(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "3");

zsets(a, "1");
zneg(b, a);
zneg(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-1");

zsets(a, "2");
zneg(b, a);
zneg(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-2");

zsets(a, "1");
zneg(b, a);
zneg(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-1");


/* zlsh */
zsets(a, "3");
zlsh(b, a, 0);
zlsh(a, a, 0);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "3");

zsets(a, "-1");
zlsh(b, a, 1);
zlsh(a, a, 1);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-2");

zsets(a, "1");
zlsh(b, a, 5);
zlsh(a, a, 5);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "32");

zsets(a, "-2");
zlsh(b, a, 0);
zlsh(a, a, 0);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-2");

zsets(a, "-1");
zlsh(b, a, 0);
zlsh(a, a, 0);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-1");


/* zrsh */
zsets(a, "0");
zrsh(b, a, 2);
zrsh(a, a, 2);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");

zsets(a, "1");
zrsh(b, a, 2);
zrsh(a, a, 2);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");

zsets(a, "1");
zrsh(b, a, 3);
zrsh(a, a, 3);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");

zsets(a, "-8");
zrsh(b, a, 2);
zrsh(a, a, 2);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-2");

zsets(a, "1");
zrsh(b, a, 3);
zrsh(a, a, 3);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");


/* ztrunc */
zsets(a, "-1");
ztrunc(b, a, 5);
ztrunc(a, a, 5);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-1");

zsets(a, "0");
ztrunc(b, a, 1);
ztrunc(a, a, 1);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");

zsets(a, "0");
ztrunc(b, a, 0);
ztrunc(a, a, 0);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");

zsets(a, "0");
ztrunc(b, a, 3);
ztrunc(a, a, 3);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");

zsets(a, "-4");
ztrunc(b, a, 4);
ztrunc(a, a, 4);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-4");


/* zsplit */
zsets(a, "0");
zset(b, a);
zsplit(b, d, b, 1);
assert_s(zstr(b, buf), "0");
assert_s(zstr(d, buf), "0");
zsplit(c, d, a, 1);
assert(zcmp(b, c), == 0);
assert_s(zstr(d, buf), "0");
zsplit(c, a, a, 1);
assert(zcmp(a, d), == 0);
assert(zcmp(b, c), == 0);

zsets(a, "1");
zset(b, a);
zsplit(b, d, b, 6);
assert_s(zstr(b, buf), "0");
assert_s(zstr(d, buf), "1");
zsplit(c, d, a, 6);
assert(zcmp(b, c), == 0);
assert_s(zstr(d, buf), "1");
zsplit(c, a, a, 6);
assert(zcmp(a, d), == 0);
assert(zcmp(b, c), == 0);

zsets(a, "2");
zset(b, a);
zsplit(b, d, b, 0);
assert_s(zstr(b, buf), "2");
assert_s(zstr(d, buf), "0");
zsplit(c, d, a, 0);
assert(zcmp(b, c), == 0);
assert_s(zstr(d, buf), "0");
zsplit(c, a, a, 0);
assert(zcmp(a, d), == 0);
assert(zcmp(b, c), == 0);

zsets(a, "1");
zset(b, a);
zsplit(b, d, b, 5);
assert_s(zstr(b, buf), "0");
assert_s(zstr(d, buf), "1");
zsplit(c, d, a, 5);
assert(zcmp(b, c), == 0);
assert_s(zstr(d, buf), "1");
zsplit(c, a, a, 5);
assert(zcmp(a, d), == 0);
assert(zcmp(b, c), == 0);

zsets(a, "7");
zset(b, a);
zsplit(b, d, b, 0);
assert_s(zstr(b, buf), "7");
assert_s(zstr(d, buf), "0");
zsplit(c, d, a, 0);
assert(zcmp(b, c), == 0);
assert_s(zstr(d, buf), "0");
zsplit(c, a, a, 0);
assert(zcmp(a, d), == 0);
assert(zcmp(b, c), == 0);


/* zand */
zsets(a, "0");
zsets(b, "-8");
zand(c, a, b);
zset(d, b);
zand(d, a, d);
zand(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");
zsets(a, "0");
zand(d, a, a);
zand(a, a, a);
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");

zsets(a, "0");
zsets(b, "-1");
zand(c, a, b);
zset(d, b);
zand(d, a, d);
zand(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");
zsets(a, "0");
zand(d, a, a);
zand(a, a, a);
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");

zsets(a, "1");
zsets(b, "2");
zand(c, a, b);
zset(d, b);
zand(d, a, d);
zand(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");
zsets(a, "1");
zand(d, a, a);
zand(a, a, a);
assert_s(zstr(d, buf), "1");
assert_s(zstr(a, buf), "1");

zsets(a, "-1");
zsets(b, "4");
zand(c, a, b);
zset(d, b);
zand(d, a, d);
zand(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zand(d, a, a);
zand(a, a, a);
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");

zsets(a, "2");
zsets(b, "-2");
zand(c, a, b);
zset(d, b);
zand(d, a, d);
zand(a, a, b);
assert_s(zstr(c, buf), "2");
assert_s(zstr(d, buf), "2");
assert_s(zstr(a, buf), "2");
zsets(a, "2");
zand(d, a, a);
zand(a, a, a);
assert_s(zstr(d, buf), "2");
assert_s(zstr(a, buf), "2");


/* zor */
zsets(a, "-1");
zsets(b, "-1");
zor(c, a, b);
zset(d, b);
zor(d, a, d);
zor(a, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");
zsets(a, "-1");
zor(d, a, a);
zor(a, a, a);
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");

zsets(a, "-1");
zsets(b, "-6");
zor(c, a, b);
zset(d, b);
zor(d, a, d);
zor(a, a, b);
assert_s(zstr(c, buf), "-7");
assert_s(zstr(d, buf), "-7");
assert_s(zstr(a, buf), "-7");
zsets(a, "-1");
zor(d, a, a);
zor(a, a, a);
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");

zsets(a, "-1");
zsets(b, "1");
zor(c, a, b);
zset(d, b);
zor(d, a, d);
zor(a, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");
zsets(a, "-1");
zor(d, a, a);
zor(a, a, a);
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");

zsets(a, "-2");
zsets(b, "8");
zor(c, a, b);
zset(d, b);
zor(d, a, d);
zor(a, a, b);
assert_s(zstr(c, buf), "-10");
assert_s(zstr(d, buf), "-10");
assert_s(zstr(a, buf), "-10");
zsets(a, "-2");
zor(d, a, a);
zor(a, a, a);
assert_s(zstr(d, buf), "-2");
assert_s(zstr(a, buf), "-2");

zsets(a, "0");
zsets(b, "1");
zor(c, a, b);
zset(d, b);
zor(d, a, d);
zor(a, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "1");
assert_s(zstr(a, buf), "1");
zsets(a, "0");
zor(d, a, a);
zor(a, a, a);
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");


/* zxor */
zsets(a, "-2");
zsets(b, "2");
zxor(c, a, b);
zset(d, b);
zxor(d, a, d);
zxor(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zxor(d, a, a);
zxor(a, a, a);
assert(zzero(d), == 1);
assert(zzero(a), == 1);

zsets(a, "-2");
zsets(b, "8");
zxor(c, a, b);
zset(d, b);
zxor(d, a, d);
zxor(a, a, b);
assert_s(zstr(c, buf), "-10");
assert_s(zstr(d, buf), "-10");
assert_s(zstr(a, buf), "-10");
zsets(a, "-2");
zxor(d, a, a);
zxor(a, a, a);
assert(zzero(d), == 1);
assert(zzero(a), == 1);

zsets(a, "1");
zsets(b, "-1");
zxor(c, a, b);
zset(d, b);
zxor(d, a, d);
zxor(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");
zsets(a, "1");
zxor(d, a, a);
zxor(a, a, a);
assert(zzero(d), == 1);
assert(zzero(a), == 1);

zsets(a, "-2");
zsets(b, "-4");
zxor(c, a, b);
zset(d, b);
zxor(d, a, d);
zxor(a, a, b);
assert_s(zstr(c, buf), "6");
assert_s(zstr(d, buf), "6");
assert_s(zstr(a, buf), "6");
zsets(a, "-2");
zxor(d, a, a);
zxor(a, a, a);
assert(zzero(d), == 1);
assert(zzero(a), == 1);

zsets(a, "-2");
zsets(b, "4");
zxor(c, a, b);
zset(d, b);
zxor(d, a, d);
zxor(a, a, b);
assert_s(zstr(c, buf), "-6");
assert_s(zstr(d, buf), "-6");
assert_s(zstr(a, buf), "-6");
zsets(a, "-2");
zxor(d, a, a);
zxor(a, a, a);
assert(zzero(d), == 1);
assert(zzero(a), == 1);


/* zbits */
zsets(a, "5");
assert_zu(zbits(a), 3);

zsets(a, "-1");
assert_zu(zbits(a), 1);

zsets(a, "0");
assert_zu(zbits(a), 1);

zsets(a, "-1");
assert_zu(zbits(a), 1);

zsets(a, "-7");
assert_zu(zbits(a), 3);


/* zlsb */
zsets(a, "0");
assert_zu(zlsb(a), SIZE_MAX);

zsets(a, "1");
assert_zu(zlsb(a), 0);

zsets(a, "1");
assert_zu(zlsb(a), 0);

zsets(a, "0");
assert_zu(zlsb(a), SIZE_MAX);

zsets(a, "-1");
assert_zu(zlsb(a), 0);


/* znot */
zsets(a, "3");
zsets(c, "0");
znot(b, a);
znot(a, a);
assert(zcmp(b, c), == 0);
assert(zcmp(a, c), == 0);

zsets(a, "-2");
zsets(c, "1");
znot(b, a);
znot(a, a);
assert(zcmp(b, c), == 0);
assert(zcmp(a, c), == 0);

zsets(a, "3");
zsets(c, "0");
znot(b, a);
znot(a, a);
assert(zcmp(b, c), == 0);
assert(zcmp(a, c), == 0);

zsets(a, "-2");
zsets(c, "1");
znot(b, a);
znot(a, a);
assert(zcmp(b, c), == 0);
assert(zcmp(a, c), == 0);

zsets(a, "-8");
zsets(c, "7");
znot(b, a);
znot(a, a);
assert(zcmp(b, c), == 0);
assert(zcmp(a, c), == 0);


/* zbtest */
zsets(a, "2");
assert(zbtest(a, 6), == 0);

zsets(a, "2");
assert(zbtest(a, 2), == 0);

zsets(a, "-4");
assert(zbtest(a, 5), == 0);

zsets(a, "1");
assert(zbtest(a, 4), == 0);

zsets(a, "2");
assert(zbtest(a, 0), == 0);


/* zbset */
zsets(a, "-7");
zset(d, a);
zbset(b, a, 2, 1);
assert_s(zstr(b, buf), "-7");
zbset(b, a, 2, 0);
assert_s(zstr(b, buf), "-3");
zbset(b, a, 2, -1);
assert_s(zstr(b, buf), "-3");
zset(a, d);
zbset(a, a, 2, 1);
assert_s(zstr(a, buf), "-7");
zset(a, d);
zbset(a, a, 2, 0);
assert_s(zstr(a, buf), "-3");
zset(a, d);
zbset(a, a, 2, -1);
assert_s(zstr(a, buf), "-3");

zsets(a, "3");
zset(d, a);
zbset(b, a, 1, 1);
assert_s(zstr(b, buf), "3");
zbset(b, a, 1, 0);
assert_s(zstr(b, buf), "1");
zbset(b, a, 1, -1);
assert_s(zstr(b, buf), "1");
zset(a, d);
zbset(a, a, 1, 1);
assert_s(zstr(a, buf), "3");
zset(a, d);
zbset(a, a, 1, 0);
assert_s(zstr(a, buf), "1");
zset(a, d);
zbset(a, a, 1, -1);
assert_s(zstr(a, buf), "1");

zsets(a, "2");
zset(d, a);
zbset(b, a, 5, 1);
assert_s(zstr(b, buf), "34");
zbset(b, a, 5, 0);
assert_s(zstr(b, buf), "2");
zbset(b, a, 5, -1);
assert_s(zstr(b, buf), "34");
zset(a, d);
zbset(a, a, 5, 1);
assert_s(zstr(a, buf), "34");
zset(a, d);
zbset(a, a, 5, 0);
assert_s(zstr(a, buf), "2");
zset(a, d);
zbset(a, a, 5, -1);
assert_s(zstr(a, buf), "34");

zsets(a, "1");
zset(d, a);
zbset(b, a, 5, 1);
assert_s(zstr(b, buf), "33");
zbset(b, a, 5, 0);
assert_s(zstr(b, buf), "1");
zbset(b, a, 5, -1);
assert_s(zstr(b, buf), "33");
zset(a, d);
zbset(a, a, 5, 1);
assert_s(zstr(a, buf), "33");
zset(a, d);
zbset(a, a, 5, 0);
assert_s(zstr(a, buf), "1");
zset(a, d);
zbset(a, a, 5, -1);
assert_s(zstr(a, buf), "33");

zsets(a, "-2");
zset(d, a);
zbset(b, a, 6, 1);
assert_s(zstr(b, buf), "-66");
zbset(b, a, 6, 0);
assert_s(zstr(b, buf), "-2");
zbset(b, a, 6, -1);
assert_s(zstr(b, buf), "-66");
zset(a, d);
zbset(a, a, 6, 1);
assert_s(zstr(a, buf), "-66");
zset(a, d);
zbset(a, a, 6, 0);
assert_s(zstr(a, buf), "-2");
zset(a, d);
zbset(a, a, 6, -1);
assert_s(zstr(a, buf), "-66");


/* zadd_unsigned */
zsets(a, "0");
zsets(b, "0");
zadd_unsigned(c, a, b);
zset(d, b);
zadd_unsigned(d, a, d);
zadd_unsigned(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");
zadd_unsigned(c, b, b);
zadd_unsigned(b, b, b);
assert_s(zstr(c, buf), "0");
assert(zcmp(b, c), == 0);

zsets(a, "7");
zsets(b, "1");
zadd_unsigned(c, a, b);
zset(d, b);
zadd_unsigned(d, a, d);
zadd_unsigned(a, a, b);
assert_s(zstr(c, buf), "8");
assert_s(zstr(d, buf), "8");
assert_s(zstr(a, buf), "8");
zadd_unsigned(c, b, b);
zadd_unsigned(b, b, b);
assert_s(zstr(c, buf), "2");
assert(zcmp(b, c), == 0);

zsets(a, "1");
zsets(b, "-8");
zadd_unsigned(c, a, b);
zset(d, b);
zadd_unsigned(d, a, d);
zadd_unsigned(a, a, b);
assert_s(zstr(c, buf), "9");
assert_s(zstr(d, buf), "9");
assert_s(zstr(a, buf), "9");
zadd_unsigned(c, b, b);
zadd_unsigned(b, b, b);
assert_s(zstr(c, buf), "16");
assert(zcmp(b, c), == 0);

zsets(a, "-4");
zsets(b, "-3");
zadd_unsigned(c, a, b);
zset(d, b);
zadd_unsigned(d, a, d);
zadd_unsigned(a, a, b);
assert_s(zstr(c, buf), "7");
assert_s(zstr(d, buf), "7");
assert_s(zstr(a, buf), "7");
zadd_unsigned(c, b, b);
zadd_unsigned(b, b, b);
assert_s(zstr(c, buf), "6");
assert(zcmp(b, c), == 0);

zsets(a, "4");
zsets(b, "1");
zadd_unsigned(c, a, b);
zset(d, b);
zadd_unsigned(d, a, d);
zadd_unsigned(a, a, b);
assert_s(zstr(c, buf), "5");
assert_s(zstr(d, buf), "5");
assert_s(zstr(a, buf), "5");
zadd_unsigned(c, b, b);
zadd_unsigned(b, b, b);
assert_s(zstr(c, buf), "2");
assert(zcmp(b, c), == 0);


/* zsub_unsigned */
zsets(a, "3");
zsets(b, "1");
zsub_unsigned(c, a, b);
zset(d, b);
zsub_unsigned(d, a, d);
zsub_unsigned(a, a, b);
assert_s(zstr(c, buf), "2");
assert_s(zstr(d, buf), "2");
assert_s(zstr(a, buf), "2");
zsub_unsigned(a, b, b);
assert(zzero(a), == 1);
zsub_unsigned(b, b, b);
assert(zzero(b), == 1);

zsets(a, "0");
zsets(b, "-6");
zsub_unsigned(c, a, b);
zset(d, b);
zsub_unsigned(d, a, d);
zsub_unsigned(a, a, b);
assert_s(zstr(c, buf), "-6");
assert_s(zstr(d, buf), "-6");
assert_s(zstr(a, buf), "-6");
zsub_unsigned(a, b, b);
assert(zzero(a), == 1);
zsub_unsigned(b, b, b);
assert(zzero(b), == 1);

zsets(a, "4");
zsets(b, "-2");
zsub_unsigned(c, a, b);
zset(d, b);
zsub_unsigned(d, a, d);
zsub_unsigned(a, a, b);
assert_s(zstr(c, buf), "2");
assert_s(zstr(d, buf), "2");
assert_s(zstr(a, buf), "2");
zsub_unsigned(a, b, b);
assert(zzero(a), == 1);
zsub_unsigned(b, b, b);
assert(zzero(b), == 1);

zsets(a, "2");
zsets(b, "-7");
zsub_unsigned(c, a, b);
zset(d, b);
zsub_unsigned(d, a, d);
zsub_unsigned(a, a, b);
assert_s(zstr(c, buf), "-5");
assert_s(zstr(d, buf), "-5");
assert_s(zstr(a, buf), "-5");
zsub_unsigned(a, b, b);
assert(zzero(a), == 1);
zsub_unsigned(b, b, b);
assert(zzero(b), == 1);

zsets(a, "2");
zsets(b, "0");
zsub_unsigned(c, a, b);
zset(d, b);
zsub_unsigned(d, a, d);
zsub_unsigned(a, a, b);
assert_s(zstr(c, buf), "2");
assert_s(zstr(d, buf), "2");
assert_s(zstr(a, buf), "2");
zsub_unsigned(a, b, b);
assert(zzero(a), == 1);
zsub_unsigned(b, b, b);
assert(zzero(b), == 1);


/* zadd */
zsets(a, "3");
zsets(b, "-2");
zadd(c, a, b);
zset(d, b);
zadd(d, a, d);
zadd(a, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "1");
assert_s(zstr(a, buf), "1");

zsets(a, "2");
zsets(b, "-2");
zadd(c, a, b);
zset(d, b);
zadd(d, a, d);
zadd(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");

zsets(a, "7");
zsets(b, "-4");
zadd(c, a, b);
zset(d, b);
zadd(d, a, d);
zadd(a, a, b);
assert_s(zstr(c, buf), "3");
assert_s(zstr(d, buf), "3");
assert_s(zstr(a, buf), "3");

zsets(a, "1");
zsets(b, "-1");
zadd(c, a, b);
zset(d, b);
zadd(d, a, d);
zadd(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");

zsets(a, "-4");
zsets(b, "-1");
zadd(c, a, b);
zset(d, b);
zadd(d, a, d);
zadd(a, a, b);
assert_s(zstr(c, buf), "-5");
assert_s(zstr(d, buf), "-5");
assert_s(zstr(a, buf), "-5");


/* zsub */
zsets(a, "1");
zsets(b, "0");
zsub(c, a, b);
zset(d, b);
zsub(d, a, d);
zsub(a, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "1");
assert_s(zstr(a, buf), "1");

zsets(a, "7");
zsets(b, "1");
zsub(c, a, b);
zset(d, b);
zsub(d, a, d);
zsub(a, a, b);
assert_s(zstr(c, buf), "6");
assert_s(zstr(d, buf), "6");
assert_s(zstr(a, buf), "6");

zsets(a, "8");
zsets(b, "0");
zsub(c, a, b);
zset(d, b);
zsub(d, a, d);
zsub(a, a, b);
assert_s(zstr(c, buf), "8");
assert_s(zstr(d, buf), "8");
assert_s(zstr(a, buf), "8");

zsets(a, "1");
zsets(b, "2");
zsub(c, a, b);
zset(d, b);
zsub(d, a, d);
zsub(a, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");

zsets(a, "1");
zsets(b, "4");
zsub(c, a, b);
zset(d, b);
zsub(d, a, d);
zsub(a, a, b);
assert_s(zstr(c, buf), "-3");
assert_s(zstr(d, buf), "-3");
assert_s(zstr(a, buf), "-3");


/* zmul */
zsets(a, "0");
zsets(b, "-4");
zsets(d, "0");
zmul(c, a, b);
assert(zcmp(c, d), == 0);
zmul(c, b, a);
assert(zcmp(c, d), == 0);
zmul(a, a, b);
assert(zcmp(a, d), == 0);
zsets(a, "0");
zmul(b, a, b);
assert(zcmp(b, d), == 0);
zsets(d, "0");
zmul(c, a, a);
assert(zcmp(c, d), == 0);
zmul(a, a, a);
assert(zcmp(a, d), == 0);

zsets(a, "2");
zsets(b, "1");
zsets(d, "2");
zmul(c, a, b);
assert(zcmp(c, d), == 0);
zmul(c, b, a);
assert(zcmp(c, d), == 0);
zmul(a, a, b);
assert(zcmp(a, d), == 0);
zsets(a, "2");
zmul(b, a, b);
assert(zcmp(b, d), == 0);
zsets(d, "4");
zmul(c, a, a);
assert(zcmp(c, d), == 0);
zmul(a, a, a);
assert(zcmp(a, d), == 0);

zsets(a, "4");
zsets(b, "4");
zsets(d, "16");
zmul(c, a, b);
assert(zcmp(c, d), == 0);
zmul(c, b, a);
assert(zcmp(c, d), == 0);
zmul(a, a, b);
assert(zcmp(a, d), == 0);
zsets(a, "4");
zmul(b, a, b);
assert(zcmp(b, d), == 0);
zsets(d, "16");
zmul(c, a, a);
assert(zcmp(c, d), == 0);
zmul(a, a, a);
assert(zcmp(a, d), == 0);

zsets(a, "2");
zsets(b, "-2");
zsets(d, "-4");
zmul(c, a, b);
assert(zcmp(c, d), == 0);
zmul(c, b, a);
assert(zcmp(c, d), == 0);
zmul(a, a, b);
assert(zcmp(a, d), == 0);
zsets(a, "2");
zmul(b, a, b);
assert(zcmp(b, d), == 0);
zsets(d, "4");
zmul(c, a, a);
assert(zcmp(c, d), == 0);
zmul(a, a, a);
assert(zcmp(a, d), == 0);

zsets(a, "1");
zsets(b, "0");
zsets(d, "0");
zmul(c, a, b);
assert(zcmp(c, d), == 0);
zmul(c, b, a);
assert(zcmp(c, d), == 0);
zmul(a, a, b);
assert(zcmp(a, d), == 0);
zsets(a, "1");
zmul(b, a, b);
assert(zcmp(b, d), == 0);
zsets(d, "1");
zmul(c, a, a);
assert(zcmp(c, d), == 0);
zmul(a, a, a);
assert(zcmp(a, d), == 0);


/* zsqr */
zsets(a, "1");
zsets(d, "1");
zsqr(c, a);
assert(zcmp(c, d), == 0);
zsqr(a, a);
assert(zcmp(a, d), == 0);

zsets(a, "-3");
zsets(d, "9");
zsqr(c, a);
assert(zcmp(c, d), == 0);
zsqr(a, a);
assert(zcmp(a, d), == 0);

zsets(a, "-4");
zsets(d, "16");
zsqr(c, a);
assert(zcmp(c, d), == 0);
zsqr(a, a);
assert(zcmp(a, d), == 0);

zsets(a, "3");
zsets(d, "9");
zsqr(c, a);
assert(zcmp(c, d), == 0);
zsqr(a, a);
assert(zcmp(a, d), == 0);

zsets(a, "4");
zsets(d, "16");
zsqr(c, a);
assert(zcmp(c, d), == 0);
zsqr(a, a);
assert(zcmp(a, d), == 0);


/* zdivmod */
zsets(a, "2");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "2");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "2");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "2");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "2");
assert_s(zstr(d, buf), "0");
zsets(a, "2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "2");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "2");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-2");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "2");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "2");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-2");
assert_s(zstr(d, buf), "0");
zsets(a, "2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-2");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-2");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-2");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-2");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-2");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-2");
assert_s(zstr(d, buf), "0");
zsets(a, "-2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-2");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-2");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "2");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-2");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-2");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "2");
assert_s(zstr(d, buf), "0");
zsets(a, "-2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "2");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");

zsets(a, "1");
zsets(b, "2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "2");
zsets(b, "2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "2");
zsets(b, "2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "2");
zsets(b, "2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "-2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "-2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "-2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "2");
zsets(b, "-2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "2");
zsets(b, "-2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "2");
zsets(b, "-2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "-2");
zsets(b, "2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-2");
zsets(b, "2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-2");
zsets(b, "2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "-2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "-2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "-2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "-2");
zsets(b, "-2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-2");
zsets(b, "-2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-2");
zsets(b, "-2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");

zsets(a, "0");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "0");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "0");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "0");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");

zsets(a, "0");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "0");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "0");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "0");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");

zsets(a, "1");
zsets(b, "2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "2");
zsets(b, "2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "2");
zsets(b, "2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "2");
zsets(b, "2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "-2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "-2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "-2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "2");
zsets(b, "-2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "2");
zsets(b, "-2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "2");
zsets(b, "-2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "-2");
zsets(b, "2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-2");
zsets(b, "2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-2");
zsets(b, "2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "-2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "-2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "-2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "-2");
zsets(b, "-2");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-2");
zsets(b, "-2");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-2");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-2");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-2");
zsets(b, "-2");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-2");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");


/* zdiv */
zsets(a, "-1");
zsets(b, "-1");
zsets(d, "1");
zdiv(c, a, b);
zdiv(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zdiv(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-1");
zsets(b, "-4");
zsets(d, "0");
zdiv(c, a, b);
zdiv(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zdiv(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-3");
zsets(b, "1");
zsets(d, "-3");
zdiv(c, a, b);
zdiv(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-3");
zdiv(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "4");
zsets(b, "-1");
zsets(d, "-4");
zdiv(c, a, b);
zdiv(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "4");
zdiv(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-2");
zsets(b, "2");
zsets(d, "-1");
zdiv(c, a, b);
zdiv(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-2");
zdiv(b, a, b);
assert(zcmp(b, d), == 0);


/* zmod */
zsets(a, "0");
zsets(b, "2");
zsets(d, "0");
zmod(c, a, b);
zmod(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "0");
zmod(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "1");
zsets(b, "-5");
zsets(d, "1");
zmod(c, a, b);
zmod(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "1");
zmod(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-8");
zsets(b, "3");
zsets(d, "2");
zmod(c, a, b);
zmod(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-8");
zmod(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "2");
zsets(b, "3");
zsets(d, "2");
zmod(c, a, b);
zmod(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "2");
zmod(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-1");
zsets(b, "7");
zsets(d, "1");
zmod(c, a, b);
zmod(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zmod(b, a, b);
assert(zcmp(b, d), == 0);


/* zmodmul */
zsets(a, "0");
zsets(b, "1");
zsets(c, "2");
zmodmul(d, a, b, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, b, c);
assert_s(zstr(a, buf), "0");
zsets(a, "0");
zmodmul(b, a, b, c);
assert_s(zstr(b, buf), "0");
zsets(b, "1");
zmodmul(c, a, b, c);
assert_s(zstr(c, buf), "0");
zsets(c, "2");
zmodmul(d, b, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, b, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "0");
zmodmul(b, b, a, c);
assert_s(zstr(b, buf), "0");
zsets(b, "1");
zmodmul(c, b, a, c);
assert_s(zstr(c, buf), "0");
zsets(c, "2");
zmodmul(d, a, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "0");
zmodmul(c, a, a, c);
assert_s(zstr(c, buf), "0");

zsets(a, "-1");
zsets(b, "0");
zsets(c, "3");
zmodmul(d, a, b, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, b, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, a, b, c);
assert_s(zstr(b, buf), "0");
zsets(b, "0");
zmodmul(c, a, b, c);
assert_s(zstr(c, buf), "0");
zsets(c, "3");
zmodmul(d, b, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, b, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, b, a, c);
assert_s(zstr(b, buf), "0");
zsets(b, "0");
zmodmul(c, b, a, c);
assert_s(zstr(c, buf), "0");
zsets(c, "3");
zmodmul(d, a, a, c);
assert_s(zstr(d, buf), "1");
zmodmul(a, a, a, c);
assert_s(zstr(a, buf), "1");
zsets(a, "-1");
zmodmul(c, a, a, c);
assert_s(zstr(c, buf), "1");
zsets(d, "0");
zmodmul(c, a, b, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, a, b, a);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, a, b, a);
assert_s(zstr(b, buf), "0");
zsets(b, "0");
zmodmul(c, b, a, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, b, a, a);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, b, a, a);
assert_s(zstr(b, buf), "0");
zmodmul(b, a, a, a);
assert(zzero(b), == 1);
zmodmul(a, a, a, a);
assert(zzero(a), == 1);

zsets(a, "-1");
zsets(b, "6");
zsets(c, "-1");
zmodmul(d, a, b, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, b, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, a, b, c);
assert_s(zstr(b, buf), "0");
zsets(b, "6");
zmodmul(c, a, b, c);
assert_s(zstr(c, buf), "0");
zsets(c, "-1");
zmodmul(d, b, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, b, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, b, a, c);
assert_s(zstr(b, buf), "0");
zsets(b, "6");
zmodmul(c, b, a, c);
assert_s(zstr(c, buf), "0");
zsets(c, "-1");
zmodmul(d, a, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(c, a, a, c);
assert_s(zstr(c, buf), "0");
zsets(d, "0");
zmodmul(c, a, b, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, a, b, a);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, a, b, a);
assert_s(zstr(b, buf), "0");
zsets(b, "6");
zmodmul(c, b, a, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, b, a, a);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, b, a, a);
assert_s(zstr(b, buf), "0");
zmodmul(b, a, a, a);
assert(zzero(b), == 1);
zmodmul(a, a, a, a);
assert(zzero(a), == 1);

zsets(a, "1");
zsets(b, "1");
zsets(c, "1");
zmodmul(d, a, b, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, b, c);
assert_s(zstr(a, buf), "0");
zsets(a, "1");
zmodmul(b, a, b, c);
assert_s(zstr(b, buf), "0");
zsets(b, "1");
zmodmul(c, a, b, c);
assert_s(zstr(c, buf), "0");
zsets(c, "1");
zmodmul(d, b, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, b, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "1");
zmodmul(b, b, a, c);
assert_s(zstr(b, buf), "0");
zsets(b, "1");
zmodmul(c, b, a, c);
assert_s(zstr(c, buf), "0");
zsets(c, "1");
zmodmul(d, a, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "1");
zmodmul(c, a, a, c);
assert_s(zstr(c, buf), "0");
zsets(d, "0");
zmodmul(c, a, b, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, a, b, a);
assert_s(zstr(a, buf), "0");
zsets(a, "1");
zmodmul(b, a, b, a);
assert_s(zstr(b, buf), "0");
zsets(b, "1");
zmodmul(c, b, a, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, b, a, a);
assert_s(zstr(a, buf), "0");
zsets(a, "1");
zmodmul(b, b, a, a);
assert_s(zstr(b, buf), "0");
zmodmul(b, a, a, a);
assert(zzero(b), == 1);
zmodmul(a, a, a, a);
assert(zzero(a), == 1);

zsets(a, "4");
zsets(b, "-1");
zsets(c, "-5");
zmodmul(d, a, b, c);
assert_s(zstr(d, buf), "4");
zmodmul(a, a, b, c);
assert_s(zstr(a, buf), "4");
zsets(a, "4");
zmodmul(b, a, b, c);
assert_s(zstr(b, buf), "4");
zsets(b, "-1");
zmodmul(c, a, b, c);
assert_s(zstr(c, buf), "4");
zsets(c, "-5");
zmodmul(d, b, a, c);
assert_s(zstr(d, buf), "4");
zmodmul(a, b, a, c);
assert_s(zstr(a, buf), "4");
zsets(a, "4");
zmodmul(b, b, a, c);
assert_s(zstr(b, buf), "4");
zsets(b, "-1");
zmodmul(c, b, a, c);
assert_s(zstr(c, buf), "4");
zsets(c, "-5");
zmodmul(d, a, a, c);
assert_s(zstr(d, buf), "1");
zmodmul(a, a, a, c);
assert_s(zstr(a, buf), "1");
zsets(a, "4");
zmodmul(c, a, a, c);
assert_s(zstr(c, buf), "1");
zsets(d, "0");
zmodmul(c, a, b, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, a, b, a);
assert_s(zstr(a, buf), "0");
zsets(a, "4");
zmodmul(b, a, b, a);
assert_s(zstr(b, buf), "0");
zsets(b, "-1");
zmodmul(c, b, a, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, b, a, a);
assert_s(zstr(a, buf), "0");
zsets(a, "4");
zmodmul(b, b, a, a);
assert_s(zstr(b, buf), "0");
zmodmul(b, a, a, a);
assert(zzero(b), == 1);
zmodmul(a, a, a, a);
assert(zzero(a), == 1);


/* zmodsqr */
zsets(a, "0");
zsets(b, "1");
zsets(d, "0");
zmodsqr(c, a, b);
assert(zcmp(c, d), == 0);
zset(c, a);
zmodsqr(a, a, b);
assert(zcmp(a, d), == 0);
zset(a, c);
zset(c, b);
zmodsqr(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "6");
zsets(b, "1");
zsets(d, "0");
zmodsqr(c, a, b);
assert(zcmp(c, d), == 0);
zset(c, a);
zmodsqr(a, a, b);
assert(zcmp(a, d), == 0);
zset(a, c);
zset(c, b);
zmodsqr(b, a, b);
assert(zcmp(b, d), == 0);
zmodsqr(b, a, a);
assert(zzero(b), == 1);
zmodsqr(a, a, a);
assert(zzero(a), == 1);

zsets(a, "7");
zsets(b, "2");
zsets(d, "1");
zmodsqr(c, a, b);
assert(zcmp(c, d), == 0);
zset(c, a);
zmodsqr(a, a, b);
assert(zcmp(a, d), == 0);
zset(a, c);
zset(c, b);
zmodsqr(b, a, b);
assert(zcmp(b, d), == 0);
zmodsqr(b, a, a);
assert(zzero(b), == 1);
zmodsqr(a, a, a);
assert(zzero(a), == 1);

zsets(a, "-1");
zsets(b, "1");
zsets(d, "0");
zmodsqr(c, a, b);
assert(zcmp(c, d), == 0);
zset(c, a);
zmodsqr(a, a, b);
assert(zcmp(a, d), == 0);
zset(a, c);
zset(c, b);
zmodsqr(b, a, b);
assert(zcmp(b, d), == 0);
zmodsqr(b, a, a);
assert(zzero(b), == 1);
zmodsqr(a, a, a);
assert(zzero(a), == 1);

zsets(a, "-8");
zsets(b, "4");
zsets(d, "0");
zmodsqr(c, a, b);
assert(zcmp(c, d), == 0);
zset(c, a);
zmodsqr(a, a, b);
assert(zcmp(a, d), == 0);
zset(a, c);
zset(c, b);
zmodsqr(b, a, b);
assert(zcmp(b, d), == 0);
zmodsqr(b, a, a);
assert(zzero(b), == 1);
zmodsqr(a, a, a);
assert(zzero(a), == 1);


/* zsave_zload */
zsets(a, "0");
n = zsave(a, 0);
assert_zu(zsave(a, buf), n);
assert_zu(zload(b, buf), n);
assert(zcmp(a, b), == 0);

zsets(a, "-4");
n = zsave(a, 0);
assert_zu(zsave(a, buf), n);
assert_zu(zload(b, buf), n);
assert(zcmp(a, b), == 0);

zsets(a, "2");
n = zsave(a, 0);
assert_zu(zsave(a, buf), n);
assert_zu(zload(b, buf), n);
assert(zcmp(a, b), == 0);

zsets(a, "0");
n = zsave(a, 0);
assert_zu(zsave(a, buf), n);
assert_zu(zload(b, buf), n);
assert(zcmp(a, b), == 0);

zsets(a, "0");
n = zsave(a, 0);
assert_zu(zsave(a, buf), n);
assert_zu(zload(b, buf), n);
assert(zcmp(a, b), == 0);


/* zgcd */
zsets(a, "-2");
zsets(b, "1");
zsets(d, "1");
zgcd(c, a, b);
assert(zcmp(c, d), == 0);

zsets(a, "4");
zsets(b, "-4");
zsets(d, "4");
zgcd(c, a, b);
assert(zcmp(c, d), == 0);

zsets(a, "0");
zsets(b, "1");
zsets(d, "1");
zgcd(c, a, b);
assert(zcmp(c, d), == 0);

zsets(a, "1");
zsets(b, "1");
zsets(d, "1");
zgcd(c, a, b);
assert(zcmp(c, d), == 0);

zsets(a, "1");
zsets(b, "1");
zsets(d, "1");
zgcd(c, a, b);
assert(zcmp(c, d), == 0);


/* zpow */
zsets(a, "-1");
zsetu(b, 2);
zsets(d, "1");
zpow(c, a, b);
zpow(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zpow(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-1");
zsetu(b, 4);
zsets(d, "1");
zpow(c, a, b);
zpow(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zpow(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "1");
zsetu(b, 1);
zsets(d, "1");
zpow(c, a, b);
zpow(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "1");
zpow(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-1");
zsetu(b, 12);
zsets(d, "1");
zpow(c, a, b);
zpow(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zpow(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-1");
zsetu(b, 14);
zsets(d, "1");
zpow(c, a, b);
zpow(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zpow(b, a, b);
assert(zcmp(b, d), == 0);


/* zpowu */
zsets(a, "7");
zsets(d, "1977326743");
zpowu(c, a, 11);
zpowu(a, a, 11);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);

zsets(a, "2");
zsets(d, "4096");
zpowu(c, a, 12);
zpowu(a, a, 12);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);

zsets(a, "-7");
zsets(d, "-7");
zpowu(c, a, 1);
zpowu(a, a, 1);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);

zsets(a, "-1");
zsets(d, "-1");
zpowu(c, a, 9);
zpowu(a, a, 9);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);

zsets(a, "5");
zsets(d, "1220703125");
zpowu(c, a, 13);
zpowu(a, a, 13);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);


/* zmodpow */
zsets(a, "1");
zsets(b, "2");
zsets(c, "-1");
zsets(d, "0");
zmodpow(d, a, b, c);
zmodpow(a, a, b, c);
assert_s(zstr(d, buf), "0");
assert(zcmp(a, d), == 0);
zsets(a, "1");
zmodpow(b, a, b, c);
assert(zcmp(b, d), == 0);
zsets(b, "2");
zmodpow(c, a, b, c);
assert(zcmp(c, d), == 0);

zsets(a, "0");
zsets(b, "1");
zsets(c, "-1");
zsets(d, "0");
zmodpow(d, a, b, c);
zmodpow(a, a, b, c);
assert_s(zstr(d, buf), "0");
assert(zcmp(a, d), == 0);
zsets(a, "0");
zmodpow(b, a, b, c);
assert(zcmp(b, d), == 0);
zsets(b, "1");
zmodpow(c, a, b, c);
assert(zcmp(c, d), == 0);

zsets(a, "2");
zsets(b, "3");
zsets(c, "2");
zsets(d, "0");
zmodpow(d, a, b, c);
zmodpow(a, a, b, c);
assert_s(zstr(d, buf), "0");
assert(zcmp(a, d), == 0);
zsets(a, "2");
zmodpow(b, a, b, c);
assert(zcmp(b, d), == 0);
zsets(b, "3");
zmodpow(c, a, b, c);
assert(zcmp(c, d), == 0);

zsets(a, "4");
zsets(b, "14");
zsets(c, "-1");
zsets(d, "0");
zmodpow(d, a, b, c);
zmodpow(a, a, b, c);
assert_s(zstr(d, buf), "0");
assert(zcmp(a, d), == 0);
zsets(a, "4");
zmodpow(b, a, b, c);
assert(zcmp(b, d), == 0);
zsets(b, "14");
zmodpow(c, a, b, c);
assert(zcmp(c, d), == 0);

zsets(a, "2");
zsets(b, "5");
zsets(c, "-5");
zsets(d, "2");
zmodpow(d, a, b, c);
zmodpow(a, a, b, c);
assert_s(zstr(d, buf), "2");
assert(zcmp(a, d), == 0);
zsets(a, "2");
zmodpow(b, a, b, c);
assert(zcmp(b, d), == 0);
zsets(b, "5");
zmodpow(c, a, b, c);
assert(zcmp(c, d), == 0);


/* zmodpowu */
zsets(a, "-2");
zsets(c, "1");
zsets(d, "0");
zmodpowu(b, a, 16, c);
zmodpowu(a, a, 16, c);
assert(zcmp(b, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-2");
zmodpowu(c, a, 16, c);
assert(zcmp(c, d), == 0);

zsets(a, "0");
zsets(c, "2");
zsets(d, "0");
zmodpowu(b, a, 7, c);
zmodpowu(a, a, 7, c);
assert(zcmp(b, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "0");
zmodpowu(c, a, 7, c);
assert(zcmp(c, d), == 0);

zsets(a, "-1");
zsets(c, "2");
zsets(d, "1");
zmodpowu(b, a, 15, c);
zmodpowu(a, a, 15, c);
assert(zcmp(b, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zmodpowu(c, a, 15, c);
assert(zcmp(c, d), == 0);

zsets(a, "1");
zsets(c, "2");
zsets(d, "1");
zmodpowu(b, a, 13, c);
zmodpowu(a, a, 13, c);
assert(zcmp(b, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "1");
zmodpowu(c, a, 13, c);
assert(zcmp(c, d), == 0);

zsets(a, "-3");
zsets(c, "-1");
zsets(d, "0");
zmodpowu(b, a, 16, c);
zmodpowu(a, a, 16, c);
assert(zcmp(b, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-3");
zmodpowu(c, a, 16, c);
assert(zcmp(c, d), == 0);


/* zstr_length */
zsets(a, "0");
assert_zu(zstr_length(a, 10), 1);

zsets(a, "0");
assert_zu(zstr_length(a, 10), 1);

zsets(a, "1");
assert_zu(zstr_length(a, 10), 1);

zsets(a, "0");
assert_zu(zstr_length(a, 10), 1);

zsets(a, "2");
assert_zu(zstr_length(a, 10), 1);


/* zstr */
zsets(a, "1");
assert_s(zstr(a, buf), "1");

zsets(a, "3");
assert_s(zstr(a, buf), "3");

zsets(a, "1");
assert_s(zstr(a, buf), "1");

zsets(a, "-2");
assert_s(zstr(a, buf), "-2");

zsets(a, "1");
assert_s(zstr(a, buf), "1");


