/* zzero */
zsets(a, "1");
assert(zzero(a), == 0);

zsets(a, "0");
assert(zzero(a), == 1);

zsets(a, "1");
assert(zzero(a), == 0);

zsets(a, "-1");
assert(zzero(a), == 0);

zsets(a, "-1");
assert(zzero(a), == 0);


/* zsignum */
zsets(a, "-1");
assert(zsignum(a), == -1);

zsets(a, "0");
assert(zsignum(a), == 0);

zsets(a, "-3");
assert(zsignum(a), == -1);

zsets(a, "1");
assert(zsignum(a), == 1);

zsets(a, "2");
assert(zsignum(a), == 1);


/* zeven_nonzero */
zsets(a, "2");
assert(zeven_nonzero(a), == 1);

zsets(a, "-8");
assert(zeven_nonzero(a), == 1);

zsets(a, "-4");
assert(zeven_nonzero(a), == 1);

zsets(a, "2");
assert(zeven_nonzero(a), == 1);

zsets(a, "-3");
assert(zeven_nonzero(a), == 0);


/* zodd_nonzero */
zsets(a, "6");
assert(zodd_nonzero(a), == 0);

zsets(a, "7");
assert(zodd_nonzero(a), == 1);

zsets(a, "-4");
assert(zodd_nonzero(a), == 0);

zsets(a, "-5");
assert(zodd_nonzero(a), == 1);

zsets(a, "3");
assert(zodd_nonzero(a), == 1);


/* zeven */
zsets(a, "1");
assert(zeven(a), == 0);

zsets(a, "-1");
assert(zeven(a), == 0);

zsets(a, "1");
assert(zeven(a), == 0);

zsets(a, "-1");
assert(zeven(a), == 0);

zsets(a, "1");
assert(zeven(a), == 0);


/* zcmp */
zsets(a, "1");
zsets(b, "0");
assert(zcmp(a, b), == 1);

zsets(a, "3");
zsets(b, "4");
assert(zcmp(a, b), == -1);

zsets(a, "0");
zsets(b, "0");
assert(zcmp(a, b), == 0);

zsets(a, "-6");
zsets(b, "1");
assert(zcmp(a, b), == -1);

zsets(a, "1");
zsets(b, "-2");
assert(zcmp(a, b), == 1);


/* zcmpi */
zsets(a, "-1");
assert(zcmpi(a, -631556921459996383LL - 1LL), == 1);

zsets(a, "-1");
assert(zcmpi(a, -860989285280235032LL - 1LL), == 1);

zsets(a, "3");
assert(zcmpi(a, 3843065909583822856LL), == -1);

zsets(a, "-8");
assert(zcmpi(a, 6380422529430794010LL), == -1);

zsets(a, "0");
assert(zcmpi(a, -4399213862147245037LL - 1LL), == 1);


/* zcmpu */
zsets(a, "2");
assert(zcmpu(a, 18126255354594005202ULL), == -1);

zsets(a, "-1");
assert(zcmpu(a, 17479879725101897725ULL), == -1);

zsets(a, "0");
assert(zcmpu(a, 11017937424768121079ULL), == -1);

zsets(a, "-4");
assert(zcmpu(a, 13760049040475088813ULL), == -1);

zsets(a, "-1");
assert(zcmpu(a, 10109002758525979270ULL), == -1);


/* zcmpmag */
zsets(a, "0");
zsets(b, "2");
assert(zcmpmag(a, b), == -1);

zsets(a, "-2");
zsets(b, "2");
assert(zcmpmag(a, b), == 0);

zsets(a, "-6");
zsets(b, "-1");
assert(zcmpmag(a, b), == 1);

zsets(a, "-3");
zsets(b, "-1");
assert(zcmpmag(a, b), == 1);

zsets(a, "3");
zsets(b, "-1");
assert(zcmpmag(a, b), == 1);


/* zodd */
zsets(a, "6");
assert(zodd(a), == 0);

zsets(a, "1");
assert(zodd(a), == 1);

zsets(a, "-1");
assert(zodd(a), == 1);

zsets(a, "-2");
assert(zodd(a), == 0);

zsets(a, "1");
assert(zodd(a), == 1);


/* zabs */
zsets(a, "-2");
zabs(b, a);
zabs(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "2");

zsets(a, "7");
zabs(b, a);
zabs(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "7");

zsets(a, "-1");
zabs(b, a);
zabs(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "1");

zsets(a, "5");
zabs(b, a);
zabs(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "5");

zsets(a, "1");
zabs(b, a);
zabs(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "1");


/* zneg */
zsets(a, "-7");
zneg(b, a);
zneg(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "7");

zsets(a, "0");
zneg(b, a);
zneg(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");

zsets(a, "2");
zneg(b, a);
zneg(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-2");

zsets(a, "1");
zneg(b, a);
zneg(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-1");

zsets(a, "4");
zneg(b, a);
zneg(a, a);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-4");


/* zlsh */
zsets(a, "4");
zlsh(b, a, 3);
zlsh(a, a, 3);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "32");

zsets(a, "-1");
zlsh(b, a, 0);
zlsh(a, a, 0);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-1");

zsets(a, "3");
zlsh(b, a, 0);
zlsh(a, a, 0);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "3");

zsets(a, "1");
zlsh(b, a, 3);
zlsh(a, a, 3);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "8");

zsets(a, "2");
zlsh(b, a, 1);
zlsh(a, a, 1);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "4");


/* zrsh */
zsets(a, "-2");
zrsh(b, a, 2);
zrsh(a, a, 2);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");

zsets(a, "2");
zrsh(b, a, 1);
zrsh(a, a, 1);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "1");

zsets(a, "-2");
zrsh(b, a, 2);
zrsh(a, a, 2);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");

zsets(a, "-1");
zrsh(b, a, 1);
zrsh(a, a, 1);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");

zsets(a, "-4");
zrsh(b, a, 3);
zrsh(a, a, 3);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");


/* ztrunc */
zsets(a, "-2");
ztrunc(b, a, 1);
ztrunc(a, a, 1);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");

zsets(a, "2");
ztrunc(b, a, 5);
ztrunc(a, a, 5);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "2");

zsets(a, "-2");
ztrunc(b, a, 3);
ztrunc(a, a, 3);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-2");

zsets(a, "-5");
ztrunc(b, a, 2);
ztrunc(a, a, 2);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "-1");

zsets(a, "0");
ztrunc(b, a, 1);
ztrunc(a, a, 1);
assert(zcmp(a, b), == 0);
assert_s(zstr(a, buf), "0");


/* zsplit */
zsets(a, "1");
zset(b, a);
zsplit(b, d, b, 6);
assert_s(zstr(b, buf), "0");
assert_s(zstr(d, buf), "1");
zsplit(c, d, a, 6);
assert(zcmp(b, c), == 0);
assert_s(zstr(d, buf), "1");
zsplit(c, a, a, 6);
assert(zcmp(a, d), == 0);
assert(zcmp(b, c), == 0);

zsets(a, "0");
zset(b, a);
zsplit(b, d, b, 3);
assert_s(zstr(b, buf), "0");
assert_s(zstr(d, buf), "0");
zsplit(c, d, a, 3);
assert(zcmp(b, c), == 0);
assert_s(zstr(d, buf), "0");
zsplit(c, a, a, 3);
assert(zcmp(a, d), == 0);
assert(zcmp(b, c), == 0);

zsets(a, "0");
zset(b, a);
zsplit(b, d, b, 3);
assert_s(zstr(b, buf), "0");
assert_s(zstr(d, buf), "0");
zsplit(c, d, a, 3);
assert(zcmp(b, c), == 0);
assert_s(zstr(d, buf), "0");
zsplit(c, a, a, 3);
assert(zcmp(a, d), == 0);
assert(zcmp(b, c), == 0);

zsets(a, "1");
zset(b, a);
zsplit(b, d, b, 1);
assert_s(zstr(b, buf), "0");
assert_s(zstr(d, buf), "1");
zsplit(c, d, a, 1);
assert(zcmp(b, c), == 0);
assert_s(zstr(d, buf), "1");
zsplit(c, a, a, 1);
assert(zcmp(a, d), == 0);
assert(zcmp(b, c), == 0);

zsets(a, "0");
zset(b, a);
zsplit(b, d, b, 3);
assert_s(zstr(b, buf), "0");
assert_s(zstr(d, buf), "0");
zsplit(c, d, a, 3);
assert(zcmp(b, c), == 0);
assert_s(zstr(d, buf), "0");
zsplit(c, a, a, 3);
assert(zcmp(a, d), == 0);
assert(zcmp(b, c), == 0);


/* zand */
zsets(a, "-1");
zsets(b, "-1");
zand(c, a, b);
zset(d, b);
zand(d, a, d);
zand(a, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");
zsets(a, "-1");
zand(d, a, a);
zand(a, a, a);
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");

zsets(a, "4");
zsets(b, "0");
zand(c, a, b);
zset(d, b);
zand(d, a, d);
zand(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");
zsets(a, "4");
zand(d, a, a);
zand(a, a, a);
assert_s(zstr(d, buf), "4");
assert_s(zstr(a, buf), "4");

zsets(a, "-1");
zsets(b, "1");
zand(c, a, b);
zset(d, b);
zand(d, a, d);
zand(a, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "1");
assert_s(zstr(a, buf), "1");
zsets(a, "-1");
zand(d, a, a);
zand(a, a, a);
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");

zsets(a, "2");
zsets(b, "2");
zand(c, a, b);
zset(d, b);
zand(d, a, d);
zand(a, a, b);
assert_s(zstr(c, buf), "2");
assert_s(zstr(d, buf), "2");
assert_s(zstr(a, buf), "2");
zsets(a, "2");
zand(d, a, a);
zand(a, a, a);
assert_s(zstr(d, buf), "2");
assert_s(zstr(a, buf), "2");

zsets(a, "-6");
zsets(b, "-1");
zand(c, a, b);
zset(d, b);
zand(d, a, d);
zand(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");
zsets(a, "-6");
zand(d, a, a);
zand(a, a, a);
assert_s(zstr(d, buf), "-6");
assert_s(zstr(a, buf), "-6");


/* zor */
zsets(a, "3");
zsets(b, "0");
zor(c, a, b);
zset(d, b);
zor(d, a, d);
zor(a, a, b);
assert_s(zstr(c, buf), "3");
assert_s(zstr(d, buf), "3");
assert_s(zstr(a, buf), "3");
zsets(a, "3");
zor(d, a, a);
zor(a, a, a);
assert_s(zstr(d, buf), "3");
assert_s(zstr(a, buf), "3");

zsets(a, "-3");
zsets(b, "6");
zor(c, a, b);
zset(d, b);
zor(d, a, d);
zor(a, a, b);
assert_s(zstr(c, buf), "-7");
assert_s(zstr(d, buf), "-7");
assert_s(zstr(a, buf), "-7");
zsets(a, "-3");
zor(d, a, a);
zor(a, a, a);
assert_s(zstr(d, buf), "-3");
assert_s(zstr(a, buf), "-3");

zsets(a, "2");
zsets(b, "-2");
zor(c, a, b);
zset(d, b);
zor(d, a, d);
zor(a, a, b);
assert_s(zstr(c, buf), "-2");
assert_s(zstr(d, buf), "-2");
assert_s(zstr(a, buf), "-2");
zsets(a, "2");
zor(d, a, a);
zor(a, a, a);
assert_s(zstr(d, buf), "2");
assert_s(zstr(a, buf), "2");

zsets(a, "-3");
zsets(b, "1");
zor(c, a, b);
zset(d, b);
zor(d, a, d);
zor(a, a, b);
assert_s(zstr(c, buf), "-3");
assert_s(zstr(d, buf), "-3");
assert_s(zstr(a, buf), "-3");
zsets(a, "-3");
zor(d, a, a);
zor(a, a, a);
assert_s(zstr(d, buf), "-3");
assert_s(zstr(a, buf), "-3");

zsets(a, "2");
zsets(b, "0");
zor(c, a, b);
zset(d, b);
zor(d, a, d);
zor(a, a, b);
assert_s(zstr(c, buf), "2");
assert_s(zstr(d, buf), "2");
assert_s(zstr(a, buf), "2");
zsets(a, "2");
zor(d, a, a);
zor(a, a, a);
assert_s(zstr(d, buf), "2");
assert_s(zstr(a, buf), "2");


/* zxor */
zsets(a, "0");
zsets(b, "1");
zxor(c, a, b);
zset(d, b);
zxor(d, a, d);
zxor(a, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "1");
assert_s(zstr(a, buf), "1");
zsets(a, "0");
zxor(d, a, a);
zxor(a, a, a);
assert(zzero(d), == 1);
assert(zzero(a), == 1);

zsets(a, "3");
zsets(b, "0");
zxor(c, a, b);
zset(d, b);
zxor(d, a, d);
zxor(a, a, b);
assert_s(zstr(c, buf), "3");
assert_s(zstr(d, buf), "3");
assert_s(zstr(a, buf), "3");
zsets(a, "3");
zxor(d, a, a);
zxor(a, a, a);
assert(zzero(d), == 1);
assert(zzero(a), == 1);

zsets(a, "-2");
zsets(b, "-1");
zxor(c, a, b);
zset(d, b);
zxor(d, a, d);
zxor(a, a, b);
assert_s(zstr(c, buf), "3");
assert_s(zstr(d, buf), "3");
assert_s(zstr(a, buf), "3");
zsets(a, "-2");
zxor(d, a, a);
zxor(a, a, a);
assert(zzero(d), == 1);
assert(zzero(a), == 1);

zsets(a, "-2");
zsets(b, "-2");
zxor(c, a, b);
zset(d, b);
zxor(d, a, d);
zxor(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zxor(d, a, a);
zxor(a, a, a);
assert(zzero(d), == 1);
assert(zzero(a), == 1);

zsets(a, "2");
zsets(b, "1");
zxor(c, a, b);
zset(d, b);
zxor(d, a, d);
zxor(a, a, b);
assert_s(zstr(c, buf), "3");
assert_s(zstr(d, buf), "3");
assert_s(zstr(a, buf), "3");
zsets(a, "2");
zxor(d, a, a);
zxor(a, a, a);
assert(zzero(d), == 1);
assert(zzero(a), == 1);


/* zbits */
zsets(a, "1");
assert_zu(zbits(a), 1);

zsets(a, "4");
assert_zu(zbits(a), 3);

zsets(a, "-3");
assert_zu(zbits(a), 2);

zsets(a, "1");
assert_zu(zbits(a), 1);

zsets(a, "-1");
assert_zu(zbits(a), 1);


/* zlsb */
zsets(a, "1");
assert_zu(zlsb(a), 0);

zsets(a, "-2");
assert_zu(zlsb(a), 1);

zsets(a, "-8");
assert_zu(zlsb(a), 3);

zsets(a, "-1");
assert_zu(zlsb(a), 0);

zsets(a, "1");
assert_zu(zlsb(a), 0);


/* znot */
zsets(a, "1");
zsets(c, "0");
znot(b, a);
znot(a, a);
assert(zcmp(b, c), == 0);
assert(zcmp(a, c), == 0);

zsets(a, "1");
zsets(c, "0");
znot(b, a);
znot(a, a);
assert(zcmp(b, c), == 0);
assert(zcmp(a, c), == 0);

zsets(a, "0");
zsets(c, "0");
znot(b, a);
znot(a, a);
assert(zcmp(b, c), == 0);
assert(zcmp(a, c), == 0);

zsets(a, "3");
zsets(c, "0");
znot(b, a);
znot(a, a);
assert(zcmp(b, c), == 0);
assert(zcmp(a, c), == 0);

zsets(a, "0");
zsets(c, "0");
znot(b, a);
znot(a, a);
assert(zcmp(b, c), == 0);
assert(zcmp(a, c), == 0);


/* zbtest */
zsets(a, "1");
assert(zbtest(a, 4), == 0);

zsets(a, "1");
assert(zbtest(a, 1), == 0);

zsets(a, "2");
assert(zbtest(a, 5), == 0);

zsets(a, "-1");
assert(zbtest(a, 6), == 0);

zsets(a, "-4");
assert(zbtest(a, 0), == 0);


/* zbset */
zsets(a, "2");
zset(d, a);
zbset(b, a, 2, 1);
assert_s(zstr(b, buf), "6");
zbset(b, a, 2, 0);
assert_s(zstr(b, buf), "2");
zbset(b, a, 2, -1);
assert_s(zstr(b, buf), "6");
zset(a, d);
zbset(a, a, 2, 1);
assert_s(zstr(a, buf), "6");
zset(a, d);
zbset(a, a, 2, 0);
assert_s(zstr(a, buf), "2");
zset(a, d);
zbset(a, a, 2, -1);
assert_s(zstr(a, buf), "6");

zsets(a, "-2");
zset(d, a);
zbset(b, a, 5, 1);
assert_s(zstr(b, buf), "-34");
zbset(b, a, 5, 0);
assert_s(zstr(b, buf), "-2");
zbset(b, a, 5, -1);
assert_s(zstr(b, buf), "-34");
zset(a, d);
zbset(a, a, 5, 1);
assert_s(zstr(a, buf), "-34");
zset(a, d);
zbset(a, a, 5, 0);
assert_s(zstr(a, buf), "-2");
zset(a, d);
zbset(a, a, 5, -1);
assert_s(zstr(a, buf), "-34");

zsets(a, "0");
zset(d, a);
zbset(b, a, 6, 1);
assert_s(zstr(b, buf), "64");
zbset(b, a, 6, 0);
assert_s(zstr(b, buf), "0");
zbset(b, a, 6, -1);
assert_s(zstr(b, buf), "64");
zset(a, d);
zbset(a, a, 6, 1);
assert_s(zstr(a, buf), "64");
zset(a, d);
zbset(a, a, 6, 0);
assert_s(zstr(a, buf), "0");
zset(a, d);
zbset(a, a, 6, -1);
assert_s(zstr(a, buf), "64");

zsets(a, "-1");
zset(d, a);
zbset(b, a, 3, 1);
assert_s(zstr(b, buf), "-9");
zbset(b, a, 3, 0);
assert_s(zstr(b, buf), "-1");
zbset(b, a, 3, -1);
assert_s(zstr(b, buf), "-9");
zset(a, d);
zbset(a, a, 3, 1);
assert_s(zstr(a, buf), "-9");
zset(a, d);
zbset(a, a, 3, 0);
assert_s(zstr(a, buf), "-1");
zset(a, d);
zbset(a, a, 3, -1);
assert_s(zstr(a, buf), "-9");

zsets(a, "-1");
zset(d, a);
zbset(b, a, 0, 1);
assert_s(zstr(b, buf), "-1");
zbset(b, a, 0, 0);
assert_s(zstr(b, buf), "0");
zbset(b, a, 0, -1);
assert_s(zstr(b, buf), "0");
zset(a, d);
zbset(a, a, 0, 1);
assert_s(zstr(a, buf), "-1");
zset(a, d);
zbset(a, a, 0, 0);
assert_s(zstr(a, buf), "0");
zset(a, d);
zbset(a, a, 0, -1);
assert_s(zstr(a, buf), "0");


/* zadd_unsigned */
zsets(a, "1");
zsets(b, "-6");
zadd_unsigned(c, a, b);
zset(d, b);
zadd_unsigned(d, a, d);
zadd_unsigned(a, a, b);
assert_s(zstr(c, buf), "7");
assert_s(zstr(d, buf), "7");
assert_s(zstr(a, buf), "7");
zadd_unsigned(c, b, b);
zadd_unsigned(b, b, b);
assert_s(zstr(c, buf), "12");
assert(zcmp(b, c), == 0);

zsets(a, "6");
zsets(b, "-3");
zadd_unsigned(c, a, b);
zset(d, b);
zadd_unsigned(d, a, d);
zadd_unsigned(a, a, b);
assert_s(zstr(c, buf), "9");
assert_s(zstr(d, buf), "9");
assert_s(zstr(a, buf), "9");
zadd_unsigned(c, b, b);
zadd_unsigned(b, b, b);
assert_s(zstr(c, buf), "6");
assert(zcmp(b, c), == 0);

zsets(a, "-4");
zsets(b, "2");
zadd_unsigned(c, a, b);
zset(d, b);
zadd_unsigned(d, a, d);
zadd_unsigned(a, a, b);
assert_s(zstr(c, buf), "6");
assert_s(zstr(d, buf), "6");
assert_s(zstr(a, buf), "6");
zadd_unsigned(c, b, b);
zadd_unsigned(b, b, b);
assert_s(zstr(c, buf), "4");
assert(zcmp(b, c), == 0);

zsets(a, "-3");
zsets(b, "1");
zadd_unsigned(c, a, b);
zset(d, b);
zadd_unsigned(d, a, d);
zadd_unsigned(a, a, b);
assert_s(zstr(c, buf), "4");
assert_s(zstr(d, buf), "4");
assert_s(zstr(a, buf), "4");
zadd_unsigned(c, b, b);
zadd_unsigned(b, b, b);
assert_s(zstr(c, buf), "2");
assert(zcmp(b, c), == 0);

zsets(a, "1");
zsets(b, "-2");
zadd_unsigned(c, a, b);
zset(d, b);
zadd_unsigned(d, a, d);
zadd_unsigned(a, a, b);
assert_s(zstr(c, buf), "3");
assert_s(zstr(d, buf), "3");
assert_s(zstr(a, buf), "3");
zadd_unsigned(c, b, b);
zadd_unsigned(b, b, b);
assert_s(zstr(c, buf), "4");
assert(zcmp(b, c), == 0);


/* zsub_unsigned */
zsets(a, "-6");
zsets(b, "0");
zsub_unsigned(c, a, b);
zset(d, b);
zsub_unsigned(d, a, d);
zsub_unsigned(a, a, b);
assert_s(zstr(c, buf), "6");
assert_s(zstr(d, buf), "6");
assert_s(zstr(a, buf), "6");
zsub_unsigned(a, b, b);
assert(zzero(a), == 1);
zsub_unsigned(b, b, b);
assert(zzero(b), == 1);

zsets(a, "-5");
zsets(b, "6");
zsub_unsigned(c, a, b);
zset(d, b);
zsub_unsigned(d, a, d);
zsub_unsigned(a, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");
zsub_unsigned(a, b, b);
assert(zzero(a), == 1);
zsub_unsigned(b, b, b);
assert(zzero(b), == 1);

zsets(a, "0");
zsets(b, "-1");
zsub_unsigned(c, a, b);
zset(d, b);
zsub_unsigned(d, a, d);
zsub_unsigned(a, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");
zsub_unsigned(a, b, b);
assert(zzero(a), == 1);
zsub_unsigned(b, b, b);
assert(zzero(b), == 1);

zsets(a, "-3");
zsets(b, "-2");
zsub_unsigned(c, a, b);
zset(d, b);
zsub_unsigned(d, a, d);
zsub_unsigned(a, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "1");
assert_s(zstr(a, buf), "1");
zsub_unsigned(a, b, b);
assert(zzero(a), == 1);
zsub_unsigned(b, b, b);
assert(zzero(b), == 1);

zsets(a, "-1");
zsets(b, "-2");
zsub_unsigned(c, a, b);
zset(d, b);
zsub_unsigned(d, a, d);
zsub_unsigned(a, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");
zsub_unsigned(a, b, b);
assert(zzero(a), == 1);
zsub_unsigned(b, b, b);
assert(zzero(b), == 1);


/* zadd */
zsets(a, "1");
zsets(b, "0");
zadd(c, a, b);
zset(d, b);
zadd(d, a, d);
zadd(a, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "1");
assert_s(zstr(a, buf), "1");

zsets(a, "0");
zsets(b, "-4");
zadd(c, a, b);
zset(d, b);
zadd(d, a, d);
zadd(a, a, b);
assert_s(zstr(c, buf), "-4");
assert_s(zstr(d, buf), "-4");
assert_s(zstr(a, buf), "-4");

zsets(a, "-1");
zsets(b, "1");
zadd(c, a, b);
zset(d, b);
zadd(d, a, d);
zadd(a, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
assert_s(zstr(a, buf), "0");

zsets(a, "-2");
zsets(b, "0");
zadd(c, a, b);
zset(d, b);
zadd(d, a, d);
zadd(a, a, b);
assert_s(zstr(c, buf), "-2");
assert_s(zstr(d, buf), "-2");
assert_s(zstr(a, buf), "-2");

zsets(a, "0");
zsets(b, "1");
zadd(c, a, b);
zset(d, b);
zadd(d, a, d);
zadd(a, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "1");
assert_s(zstr(a, buf), "1");


/* zsub */
zsets(a, "-1");
zsets(b, "0");
zsub(c, a, b);
zset(d, b);
zsub(d, a, d);
zsub(a, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "-1");
assert_s(zstr(a, buf), "-1");

zsets(a, "2");
zsets(b, "0");
zsub(c, a, b);
zset(d, b);
zsub(d, a, d);
zsub(a, a, b);
assert_s(zstr(c, buf), "2");
assert_s(zstr(d, buf), "2");
assert_s(zstr(a, buf), "2");

zsets(a, "-8");
zsets(b, "0");
zsub(c, a, b);
zset(d, b);
zsub(d, a, d);
zsub(a, a, b);
assert_s(zstr(c, buf), "-8");
assert_s(zstr(d, buf), "-8");
assert_s(zstr(a, buf), "-8");

zsets(a, "1");
zsets(b, "0");
zsub(c, a, b);
zset(d, b);
zsub(d, a, d);
zsub(a, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "1");
assert_s(zstr(a, buf), "1");

zsets(a, "1");
zsets(b, "3");
zsub(c, a, b);
zset(d, b);
zsub(d, a, d);
zsub(a, a, b);
assert_s(zstr(c, buf), "-2");
assert_s(zstr(d, buf), "-2");
assert_s(zstr(a, buf), "-2");


/* zmul */
zsets(a, "8");
zsets(b, "-1");
zsets(d, "-8");
zmul(c, a, b);
assert(zcmp(c, d), == 0);
zmul(c, b, a);
assert(zcmp(c, d), == 0);
zmul(a, a, b);
assert(zcmp(a, d), == 0);
zsets(a, "8");
zmul(b, a, b);
assert(zcmp(b, d), == 0);
zsets(d, "64");
zmul(c, a, a);
assert(zcmp(c, d), == 0);
zmul(a, a, a);
assert(zcmp(a, d), == 0);

zsets(a, "1");
zsets(b, "-1");
zsets(d, "-1");
zmul(c, a, b);
assert(zcmp(c, d), == 0);
zmul(c, b, a);
assert(zcmp(c, d), == 0);
zmul(a, a, b);
assert(zcmp(a, d), == 0);
zsets(a, "1");
zmul(b, a, b);
assert(zcmp(b, d), == 0);
zsets(d, "1");
zmul(c, a, a);
assert(zcmp(c, d), == 0);
zmul(a, a, a);
assert(zcmp(a, d), == 0);

zsets(a, "0");
zsets(b, "3");
zsets(d, "0");
zmul(c, a, b);
assert(zcmp(c, d), == 0);
zmul(c, b, a);
assert(zcmp(c, d), == 0);
zmul(a, a, b);
assert(zcmp(a, d), == 0);
zsets(a, "0");
zmul(b, a, b);
assert(zcmp(b, d), == 0);
zsets(d, "0");
zmul(c, a, a);
assert(zcmp(c, d), == 0);
zmul(a, a, a);
assert(zcmp(a, d), == 0);

zsets(a, "4");
zsets(b, "-1");
zsets(d, "-4");
zmul(c, a, b);
assert(zcmp(c, d), == 0);
zmul(c, b, a);
assert(zcmp(c, d), == 0);
zmul(a, a, b);
assert(zcmp(a, d), == 0);
zsets(a, "4");
zmul(b, a, b);
assert(zcmp(b, d), == 0);
zsets(d, "16");
zmul(c, a, a);
assert(zcmp(c, d), == 0);
zmul(a, a, a);
assert(zcmp(a, d), == 0);

zsets(a, "1");
zsets(b, "4");
zsets(d, "4");
zmul(c, a, b);
assert(zcmp(c, d), == 0);
zmul(c, b, a);
assert(zcmp(c, d), == 0);
zmul(a, a, b);
assert(zcmp(a, d), == 0);
zsets(a, "1");
zmul(b, a, b);
assert(zcmp(b, d), == 0);
zsets(d, "1");
zmul(c, a, a);
assert(zcmp(c, d), == 0);
zmul(a, a, a);
assert(zcmp(a, d), == 0);


/* zsqr */
zsets(a, "0");
zsets(d, "0");
zsqr(c, a);
assert(zcmp(c, d), == 0);
zsqr(a, a);
assert(zcmp(a, d), == 0);

zsets(a, "1");
zsets(d, "1");
zsqr(c, a);
assert(zcmp(c, d), == 0);
zsqr(a, a);
assert(zcmp(a, d), == 0);

zsets(a, "0");
zsets(d, "0");
zsqr(c, a);
assert(zcmp(c, d), == 0);
zsqr(a, a);
assert(zcmp(a, d), == 0);

zsets(a, "1");
zsets(d, "1");
zsqr(c, a);
assert(zcmp(c, d), == 0);
zsqr(a, a);
assert(zcmp(a, d), == 0);

zsets(a, "1");
zsets(d, "1");
zsqr(c, a);
assert(zcmp(c, d), == 0);
zsqr(a, a);
assert(zcmp(a, d), == 0);


/* zdivmod */
zsets(a, "1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");

zsets(a, "1");
zsets(b, "4");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "4");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "4");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "4");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "4");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "4");
zsets(b, "4");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "4");
zsets(b, "4");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "4");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "4");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "4");
zsets(b, "4");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "4");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "-4");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "-4");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-4");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-4");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "-4");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "4");
zsets(b, "-4");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "4");
zsets(b, "-4");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-4");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-4");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "4");
zsets(b, "-4");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "4");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "4");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "4");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "4");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "4");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "4");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "-4");
zsets(b, "4");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-4");
zsets(b, "4");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "4");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "4");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-4");
zsets(b, "4");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-4");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "-4");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "1");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "-4");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-4");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-4");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "-4");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "1");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "1");
zsets(a, "-4");
zsets(b, "-4");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-4");
zsets(b, "-4");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-4");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-4");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-4");
zsets(b, "-4");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-4");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");

zsets(a, "1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");

zsets(a, "0");
zsets(b, "3");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "3");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "3");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "3");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "3");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "3");
zsets(b, "3");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "3");
zsets(b, "3");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "3");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "3");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "3");
zsets(b, "3");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "3");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "0");
zsets(b, "-3");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "-3");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-3");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-3");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "-3");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "3");
zsets(b, "-3");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "3");
zsets(b, "-3");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-3");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-3");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "3");
zsets(b, "-3");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "3");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "0");
zsets(b, "3");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "3");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "3");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "3");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "3");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "-3");
zsets(b, "3");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-3");
zsets(b, "3");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "3");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "3");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-3");
zsets(b, "3");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-3");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "0");
zsets(b, "-3");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "0");
zsets(b, "-3");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-3");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-3");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "0");
zsets(b, "-3");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "0");
assert_s(zstr(d, buf), "0");
zsets(a, "0");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "0");
assert_s(zstr(b, buf), "0");
zsets(a, "-3");
zsets(b, "-3");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-3");
zsets(b, "-3");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-3");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-3");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-3");
zsets(b, "-3");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-3");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");

zsets(a, "7");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "7");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "7");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "7");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "7");
assert_s(zstr(d, buf), "0");
zsets(a, "7");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "7");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");
zsets(a, "7");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-7");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "7");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "7");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-7");
assert_s(zstr(d, buf), "0");
zsets(a, "7");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-7");
assert_s(zstr(b, buf), "0");
zsets(a, "1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-7");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-7");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-7");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-7");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-7");
assert_s(zstr(d, buf), "0");
zsets(a, "-7");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-7");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "-1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "-1");
assert_s(zstr(b, buf), "0");
zsets(a, "-7");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "7");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-7");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-7");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "7");
assert_s(zstr(d, buf), "0");
zsets(a, "-7");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "7");
assert_s(zstr(b, buf), "0");
zsets(a, "-1");
zsets(b, "-1");
zdivmod(c, d, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(d, buf), "0");
zdivmod(a, b, a, b);
assert(zcmp(a, c), == 0);
assert(zcmp(b, d), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(b, a, a, b);
assert(zcmp(b, c), == 0);
assert(zcmp(a, d), == 0);
zsets(b, "-1");
zdivmod(b, a, b, b);
assert(zcmpu(b, 1), == 0);
assert(zcmpu(a, 0), == 0);
zsets(b, "-1");
zdivmod(a, b, b, b);
assert(zcmpu(a, 1), == 0);
assert(zcmpu(b, 0), == 0);
zsets(a, "-1");
zsets(b, "-1");
zdivmod(a, d, a, b);
assert_s(zstr(a, buf), "1");
assert_s(zstr(d, buf), "0");
zsets(a, "-1");
zdivmod(c, b, a, b);
assert_s(zstr(c, buf), "1");
assert_s(zstr(b, buf), "0");


/* zdiv */
zsets(a, "-1");
zsets(b, "-2");
zsets(d, "0");
zdiv(c, a, b);
zdiv(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zdiv(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "3");
zsets(b, "1");
zsets(d, "3");
zdiv(c, a, b);
zdiv(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "3");
zdiv(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-1");
zsets(b, "1");
zsets(d, "-1");
zdiv(c, a, b);
zdiv(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zdiv(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "2");
zsets(b, "-1");
zsets(d, "-2");
zdiv(c, a, b);
zdiv(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "2");
zdiv(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "2");
zsets(b, "-2");
zsets(d, "-1");
zdiv(c, a, b);
zdiv(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "2");
zdiv(b, a, b);
assert(zcmp(b, d), == 0);


/* zmod */
zsets(a, "1");
zsets(b, "7");
zsets(d, "1");
zmod(c, a, b);
zmod(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "1");
zmod(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-1");
zsets(b, "1");
zsets(d, "0");
zmod(c, a, b);
zmod(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zmod(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "3");
zsets(b, "4");
zsets(d, "3");
zmod(c, a, b);
zmod(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "3");
zmod(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-7");
zsets(b, "-4");
zsets(d, "3");
zmod(c, a, b);
zmod(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-7");
zmod(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-1");
zsets(b, "-2");
zsets(d, "1");
zmod(c, a, b);
zmod(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zmod(b, a, b);
assert(zcmp(b, d), == 0);


/* zmodmul */
zsets(a, "2");
zsets(b, "0");
zsets(c, "4");
zmodmul(d, a, b, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, b, c);
assert_s(zstr(a, buf), "0");
zsets(a, "2");
zmodmul(b, a, b, c);
assert_s(zstr(b, buf), "0");
zsets(b, "0");
zmodmul(c, a, b, c);
assert_s(zstr(c, buf), "0");
zsets(c, "4");
zmodmul(d, b, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, b, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "2");
zmodmul(b, b, a, c);
assert_s(zstr(b, buf), "0");
zsets(b, "0");
zmodmul(c, b, a, c);
assert_s(zstr(c, buf), "0");
zsets(c, "4");
zmodmul(d, a, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "2");
zmodmul(c, a, a, c);
assert_s(zstr(c, buf), "0");
zsets(d, "0");
zmodmul(c, a, b, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, a, b, a);
assert_s(zstr(a, buf), "0");
zsets(a, "2");
zmodmul(b, a, b, a);
assert_s(zstr(b, buf), "0");
zsets(b, "0");
zmodmul(c, b, a, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, b, a, a);
assert_s(zstr(a, buf), "0");
zsets(a, "2");
zmodmul(b, b, a, a);
assert_s(zstr(b, buf), "0");
zmodmul(b, a, a, a);
assert(zzero(b), == 1);
zmodmul(a, a, a, a);
assert(zzero(a), == 1);

zsets(a, "-1");
zsets(b, "0");
zsets(c, "-1");
zmodmul(d, a, b, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, b, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, a, b, c);
assert_s(zstr(b, buf), "0");
zsets(b, "0");
zmodmul(c, a, b, c);
assert_s(zstr(c, buf), "0");
zsets(c, "-1");
zmodmul(d, b, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, b, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, b, a, c);
assert_s(zstr(b, buf), "0");
zsets(b, "0");
zmodmul(c, b, a, c);
assert_s(zstr(c, buf), "0");
zsets(c, "-1");
zmodmul(d, a, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(c, a, a, c);
assert_s(zstr(c, buf), "0");
zsets(d, "0");
zmodmul(c, a, b, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, a, b, a);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, a, b, a);
assert_s(zstr(b, buf), "0");
zsets(b, "0");
zmodmul(c, b, a, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, b, a, a);
assert_s(zstr(a, buf), "0");
zsets(a, "-1");
zmodmul(b, b, a, a);
assert_s(zstr(b, buf), "0");
zmodmul(b, a, a, a);
assert(zzero(b), == 1);
zmodmul(a, a, a, a);
assert(zzero(a), == 1);

zsets(a, "-2");
zsets(b, "-1");
zsets(c, "1");
zmodmul(d, a, b, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, b, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zmodmul(b, a, b, c);
assert_s(zstr(b, buf), "0");
zsets(b, "-1");
zmodmul(c, a, b, c);
assert_s(zstr(c, buf), "0");
zsets(c, "1");
zmodmul(d, b, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, b, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zmodmul(b, b, a, c);
assert_s(zstr(b, buf), "0");
zsets(b, "-1");
zmodmul(c, b, a, c);
assert_s(zstr(c, buf), "0");
zsets(c, "1");
zmodmul(d, a, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zmodmul(c, a, a, c);
assert_s(zstr(c, buf), "0");
zsets(d, "0");
zmodmul(c, a, b, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, a, b, a);
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zmodmul(b, a, b, a);
assert_s(zstr(b, buf), "0");
zsets(b, "-1");
zmodmul(c, b, a, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, b, a, a);
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zmodmul(b, b, a, a);
assert_s(zstr(b, buf), "0");
zmodmul(b, a, a, a);
assert(zzero(b), == 1);
zmodmul(a, a, a, a);
assert(zzero(a), == 1);

zsets(a, "2");
zsets(b, "-1");
zsets(c, "-4");
zmodmul(d, a, b, c);
assert_s(zstr(d, buf), "2");
zmodmul(a, a, b, c);
assert_s(zstr(a, buf), "2");
zsets(a, "2");
zmodmul(b, a, b, c);
assert_s(zstr(b, buf), "2");
zsets(b, "-1");
zmodmul(c, a, b, c);
assert_s(zstr(c, buf), "2");
zsets(c, "-4");
zmodmul(d, b, a, c);
assert_s(zstr(d, buf), "2");
zmodmul(a, b, a, c);
assert_s(zstr(a, buf), "2");
zsets(a, "2");
zmodmul(b, b, a, c);
assert_s(zstr(b, buf), "2");
zsets(b, "-1");
zmodmul(c, b, a, c);
assert_s(zstr(c, buf), "2");
zsets(c, "-4");
zmodmul(d, a, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "2");
zmodmul(c, a, a, c);
assert_s(zstr(c, buf), "0");
zsets(d, "0");
zmodmul(c, a, b, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, a, b, a);
assert_s(zstr(a, buf), "0");
zsets(a, "2");
zmodmul(b, a, b, a);
assert_s(zstr(b, buf), "0");
zsets(b, "-1");
zmodmul(c, b, a, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, b, a, a);
assert_s(zstr(a, buf), "0");
zsets(a, "2");
zmodmul(b, b, a, a);
assert_s(zstr(b, buf), "0");
zmodmul(b, a, a, a);
assert(zzero(b), == 1);
zmodmul(a, a, a, a);
assert(zzero(a), == 1);

zsets(a, "-2");
zsets(b, "8");
zsets(c, "1");
zmodmul(d, a, b, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, b, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zmodmul(b, a, b, c);
assert_s(zstr(b, buf), "0");
zsets(b, "8");
zmodmul(c, a, b, c);
assert_s(zstr(c, buf), "0");
zsets(c, "1");
zmodmul(d, b, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, b, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zmodmul(b, b, a, c);
assert_s(zstr(b, buf), "0");
zsets(b, "8");
zmodmul(c, b, a, c);
assert_s(zstr(c, buf), "0");
zsets(c, "1");
zmodmul(d, a, a, c);
assert_s(zstr(d, buf), "0");
zmodmul(a, a, a, c);
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zmodmul(c, a, a, c);
assert_s(zstr(c, buf), "0");
zsets(d, "0");
zmodmul(c, a, b, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, a, b, a);
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zmodmul(b, a, b, a);
assert_s(zstr(b, buf), "0");
zsets(b, "8");
zmodmul(c, b, a, a);
assert_s(zstr(c, buf), "0");
zmodmul(a, b, a, a);
assert_s(zstr(a, buf), "0");
zsets(a, "-2");
zmodmul(b, b, a, a);
assert_s(zstr(b, buf), "0");
zmodmul(b, a, a, a);
assert(zzero(b), == 1);
zmodmul(a, a, a, a);
assert(zzero(a), == 1);


/* zmodsqr */
zsets(a, "0");
zsets(b, "-2");
zsets(d, "0");
zmodsqr(c, a, b);
assert(zcmp(c, d), == 0);
zset(c, a);
zmodsqr(a, a, b);
assert(zcmp(a, d), == 0);
zset(a, c);
zset(c, b);
zmodsqr(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-1");
zsets(b, "1");
zsets(d, "0");
zmodsqr(c, a, b);
assert(zcmp(c, d), == 0);
zset(c, a);
zmodsqr(a, a, b);
assert(zcmp(a, d), == 0);
zset(a, c);
zset(c, b);
zmodsqr(b, a, b);
assert(zcmp(b, d), == 0);
zmodsqr(b, a, a);
assert(zzero(b), == 1);
zmodsqr(a, a, a);
assert(zzero(a), == 1);

zsets(a, "-4");
zsets(b, "5");
zsets(d, "1");
zmodsqr(c, a, b);
assert(zcmp(c, d), == 0);
zset(c, a);
zmodsqr(a, a, b);
assert(zcmp(a, d), == 0);
zset(a, c);
zset(c, b);
zmodsqr(b, a, b);
assert(zcmp(b, d), == 0);
zmodsqr(b, a, a);
assert(zzero(b), == 1);
zmodsqr(a, a, a);
assert(zzero(a), == 1);

zsets(a, "-5");
zsets(b, "-1");
zsets(d, "0");
zmodsqr(c, a, b);
assert(zcmp(c, d), == 0);
zset(c, a);
zmodsqr(a, a, b);
assert(zcmp(a, d), == 0);
zset(a, c);
zset(c, b);
zmodsqr(b, a, b);
assert(zcmp(b, d), == 0);
zmodsqr(b, a, a);
assert(zzero(b), == 1);
zmodsqr(a, a, a);
assert(zzero(a), == 1);

zsets(a, "1");
zsets(b, "1");
zsets(d, "0");
zmodsqr(c, a, b);
assert(zcmp(c, d), == 0);
zset(c, a);
zmodsqr(a, a, b);
assert(zcmp(a, d), == 0);
zset(a, c);
zset(c, b);
zmodsqr(b, a, b);
assert(zcmp(b, d), == 0);
zmodsqr(b, a, a);
assert(zzero(b), == 1);
zmodsqr(a, a, a);
assert(zzero(a), == 1);


/* zsave_zload */
zsets(a, "1");
n = zsave(a, 0);
assert_zu(zsave(a, buf), n);
assert_zu(zload(b, buf), n);
assert(zcmp(a, b), == 0);

zsets(a, "-1");
n = zsave(a, 0);
assert_zu(zsave(a, buf), n);
assert_zu(zload(b, buf), n);
assert(zcmp(a, b), == 0);

zsets(a, "-2");
n = zsave(a, 0);
assert_zu(zsave(a, buf), n);
assert_zu(zload(b, buf), n);
assert(zcmp(a, b), == 0);

zsets(a, "-3");
n = zsave(a, 0);
assert_zu(zsave(a, buf), n);
assert_zu(zload(b, buf), n);
assert(zcmp(a, b), == 0);

zsets(a, "-1");
n = zsave(a, 0);
assert_zu(zsave(a, buf), n);
assert_zu(zload(b, buf), n);
assert(zcmp(a, b), == 0);


/* zgcd */
zsets(a, "0");
zsets(b, "-2");
zsets(d, "-2");
zgcd(c, a, b);
assert(zcmp(c, d), == 0);

zsets(a, "-4");
zsets(b, "1");
zsets(d, "1");
zgcd(c, a, b);
assert(zcmp(c, d), == 0);

zsets(a, "-4");
zsets(b, "2");
zsets(d, "2");
zgcd(c, a, b);
assert(zcmp(c, d), == 0);

zsets(a, "-5");
zsets(b, "0");
zsets(d, "-5");
zgcd(c, a, b);
assert(zcmp(c, d), == 0);

zsets(a, "-1");
zsets(b, "1");
zsets(d, "1");
zgcd(c, a, b);
assert(zcmp(c, d), == 0);


/* zpow */
zsets(a, "-3");
zsetu(b, 4);
zsets(d, "81");
zpow(c, a, b);
zpow(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-3");
zpow(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-2");
zsetu(b, 10);
zsets(d, "1024");
zpow(c, a, b);
zpow(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-2");
zpow(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-3");
zsetu(b, 7);
zsets(d, "-2187");
zpow(c, a, b);
zpow(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-3");
zpow(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "1");
zsetu(b, 11);
zsets(d, "1");
zpow(c, a, b);
zpow(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "1");
zpow(b, a, b);
assert(zcmp(b, d), == 0);

zsets(a, "-3");
zsetu(b, 1);
zsets(d, "-3");
zpow(c, a, b);
zpow(a, a, b);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-3");
zpow(b, a, b);
assert(zcmp(b, d), == 0);


/* zpowu */
zsets(a, "-1");
zsets(d, "1");
zpowu(c, a, 8);
zpowu(a, a, 8);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);

zsets(a, "-1");
zsets(d, "1");
zpowu(c, a, 14);
zpowu(a, a, 14);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);

zsets(a, "2");
zsets(d, "65536");
zpowu(c, a, 16);
zpowu(a, a, 16);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);

zsets(a, "6");
zsets(d, "78364164096");
zpowu(c, a, 14);
zpowu(a, a, 14);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);

zsets(a, "0");
zsets(d, "0");
zpowu(c, a, 6);
zpowu(a, a, 6);
assert(zcmp(c, d), == 0);
assert(zcmp(a, d), == 0);


/* zmodpow */
zsets(a, "-1");
zsets(b, "13");
zsets(c, "1");
zsets(d, "0");
zmodpow(d, a, b, c);
zmodpow(a, a, b, c);
assert_s(zstr(d, buf), "0");
assert(zcmp(a, d), == 0);
zsets(a, "-1");
zmodpow(b, a, b, c);
assert(zcmp(b, d), == 0);
zsets(b, "13");
zmodpow(c, a, b, c);
assert(zcmp(c, d), == 0);

zsets(a, "4");
zsets(b, "1");
zsets(c, "1");
zsets(d, "0");
zmodpow(d, a, b, c);
zmodpow(a, a, b, c);
assert_s(zstr(d, buf), "0");
assert(zcmp(a, d), == 0);
zsets(a, "4");
zmodpow(b, a, b, c);
assert(zcmp(b, d), == 0);
zsets(b, "1");
zmodpow(c, a, b, c);
assert(zcmp(c, d), == 0);

zsets(a, "-4");
zsets(b, "6");
zsets(c, "-2");
zsets(d, "0");
zmodpow(d, a, b, c);
zmodpow(a, a, b, c);
assert_s(zstr(d, buf), "0");
assert(zcmp(a, d), == 0);
zsets(a, "-4");
zmodpow(b, a, b, c);
assert(zcmp(b, d), == 0);
zsets(b, "6");
zmodpow(c, a, b, c);
assert(zcmp(c, d), == 0);

zsets(a, "1");
zsets(b, "15");
zsets(c, "-2");
zsets(d, "1");
zmodpow(d, a, b, c);
zmodpow(a, a, b, c);
assert_s(zstr(d, buf), "1");
assert(zcmp(a, d), == 0);
zsets(a, "1");
zmodpow(b, a, b, c);
assert(zcmp(b, d), == 0);
zsets(b, "15");
zmodpow(c, a, b, c);
assert(zcmp(c, d), == 0);

zsets(a, "-2");
zsets(b, "4");
zsets(c, "-1");
zsets(d, "0");
zmodpow(d, a, b, c);
zmodpow(a, a, b, c);
assert_s(zstr(d, buf), "0");
assert(zcmp(a, d), == 0);
zsets(a, "-2");
zmodpow(b, a, b, c);
assert(zcmp(b, d), == 0);
zsets(b, "4");
zmodpow(c, a, b, c);
assert(zcmp(c, d), == 0);


/* zmodpowu */
zsets(a, "3");
zsets(c, "4");
zsets(d, "1");
zmodpowu(b, a, 16, c);
zmodpowu(a, a, 16, c);
assert(zcmp(b, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "3");
zmodpowu(c, a, 16, c);
assert(zcmp(c, d), == 0);

zsets(a, "2");
zsets(c, "-7");
zsets(d, "2");
zmodpowu(b, a, 16, c);
zmodpowu(a, a, 16, c);
assert(zcmp(b, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "2");
zmodpowu(c, a, 16, c);
assert(zcmp(c, d), == 0);

zsets(a, "0");
zsets(c, "-1");
zsets(d, "0");
zmodpowu(b, a, 5, c);
zmodpowu(a, a, 5, c);
assert(zcmp(b, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "0");
zmodpowu(c, a, 5, c);
assert(zcmp(c, d), == 0);

zsets(a, "-3");
zsets(c, "-1");
zsets(d, "0");
zmodpowu(b, a, 5, c);
zmodpowu(a, a, 5, c);
assert(zcmp(b, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "-3");
zmodpowu(c, a, 5, c);
assert(zcmp(c, d), == 0);

zsets(a, "0");
zsets(c, "-1");
zsets(d, "0");
zmodpowu(b, a, 10, c);
zmodpowu(a, a, 10, c);
assert(zcmp(b, d), == 0);
assert(zcmp(a, d), == 0);
zsets(a, "0");
zmodpowu(c, a, 10, c);
assert(zcmp(c, d), == 0);


/* zstr_length */
zsets(a, "-2");
assert_zu(zstr_length(a, 10), 2);

zsets(a, "0");
assert_zu(zstr_length(a, 10), 1);

zsets(a, "1");
assert_zu(zstr_length(a, 10), 1);

zsets(a, "1");
assert_zu(zstr_length(a, 10), 1);

zsets(a, "4");
assert_zu(zstr_length(a, 10), 1);


/* zstr */
zsets(a, "0");
assert_s(zstr(a, buf), "0");

zsets(a, "3");
assert_s(zstr(a, buf), "3");

zsets(a, "0");
assert_s(zstr(a, buf), "0");

zsets(a, "-1");
assert_s(zstr(a, buf), "-1");

zsets(a, "2");
assert_s(zstr(a, buf), "2");


