enum markdown_char_t
{
  MD_CHAR_NONE = 0,
  MD_CHAR_EMPHASIS,
  MD_CHAR_CODESPAN,
  MD_CHAR_LINEBREAK,
  MD_CHAR_LINK,
  MD_CHAR_LANGLE,
  MD_CHAR_ESCAPE,
  MD_CHAR_ENTITITY,
  MD_CHAR_AUTOLINK_URL,
  MD_CHAR_AUTOLINK_EMAIL,
  MD_CHAR_AUTOLINK_WWW,
  MD_CHAR_AUTOLINK_SUBREDDIT_OR_USERNAME,
  MD_CHAR_SUPERSCRIPT
}
/*** DEPENDENCIES:
***/


