enum mkd_extensions
{
  MKDEXT_NO_INTRA_EMPHASIS = 1 << 0,
  MKDEXT_TABLES = 1 << 1,
  MKDEXT_FENCED_CODE = 1 << 2,
  MKDEXT_AUTOLINK = 1 << 3,
  MKDEXT_STRIKETHROUGH = 1 << 4,
  MKDEXT_SPACE_HEADERS = 1 << 6,
  MKDEXT_SUPERSCRIPT = 1 << 7,
  MKDEXT_LAX_SPACING = 1 << 8,
  MKDEXT_NO_EMAIL_AUTOLINK = 1 << 9
}
/*** DEPENDENCIES:
***/


