[package]
name = "translate_new"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.5"

[[bin]]
name="test"
path="src/test_main.rs"

[[bin]]
name="openaptxenc"
path="src/openaptxenc.rs"

[[bin]]
name="openaptxdec"
path="src/openaptxdec.rs"
