use crate::*;

#[derive(Clone)]
pub struct LodePNGInfo {
    pub compression_method: u32,
    pub filter_method: u32,
    pub interlace_method: u32,
    pub color: LodePNGColorMode,
    pub background_defined: u32,
    pub background_r: u32,
    pub background_g: u32,
    pub background_b: u32,
    pub text_num: usize,
    pub text_keys: Option<Vec<String>>,
    pub text_strings: Option<Vec<String>>,
    pub itext_num: usize,
    pub itext_keys: Option<Vec<String>>,
    pub itext_langtags: Option<Vec<String>>,
    pub itext_transkeys: Option<Vec<String>>,
    pub itext_strings: Option<Vec<String>>,
    pub time_defined: u32,
    pub time: LodePNGTime,
    pub phys_defined: u32,
    pub phys_x: u32,
    pub phys_y: u32,
    pub phys_unit: u32,
    pub gama_defined: u32,
    pub gama_gamma: u32,
    pub chrm_defined: u32,
    pub chrm_white_x: u32,
    pub chrm_white_y: u32,
    pub chrm_red_x: u32,
    pub chrm_red_y: u32,
    pub chrm_green_x: u32,
    pub chrm_green_y: u32,
    pub chrm_blue_x: u32,
    pub chrm_blue_y: u32,
    pub srgb_defined: u32,
    pub srgb_intent: u32,
    pub iccp_defined: u32,
    pub iccp_name: Option<String>,
    pub iccp_profile: Option<Vec<u8>>,
    pub iccp_profile_size: u32,
    pub sbit_defined: u32,
    pub sbit_r: u32,
    pub sbit_g: u32,
    pub sbit_b: u32,
    pub sbit_a: u32,
    pub unknown_chunks_data: [Option<Vec<u8>>; 3],
    pub unknown_chunks_size: [usize; 3],
}

